### ISSUE TITLE
Getting error with new version

### ISSUE THREAD

**Issue by skank01** [MaxWinterstein/homeassistant-addons#10]
[url=https://ibb.co/k9RqW3r][img]https://i.ibb.co/tx7YWZN/Knipsel.jpg[/img][/url]

**Comment by MaxWinterstein** [comment]
Can you post the log files of the add on? “log” tab?

**Comment by skank01** [comment]
Snippet:
1611405349: New connection from x.x.x.x on port 1883.
1611405349: New client connected from x.x.x.X as mqttjs_6434f9f9 (p2, c1, k60, u'chris').
1611405350: Socket error on client mqttjs_6434f9f9, disconnecting.
1611405380: New connection from x.x.x.x on port 1883.
1611405380: New client connected from x.x.x.x as mqttjs_a29d4a60 (p2, c1, k60, u'chris').
1611405381: Socket error on client mqttjs_a29d4a60, disconnecting.

and so on and so on

**Comment by MaxWinterstein** [comment]
This looks like the log of the mqtt broker? I mean the log output of the addon itself.

**Comment by skank01** [comment]
ur right sorry
here:
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:22:39] INFO: Exporting log level for nodejs: info
[19:22:39] INFO: Symlinking data dir
[19:22:39] INFO: Generating config.yml from options.json
[19:22:39] INFO: Image build with version 0.2.4
[19:22:39] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-01-23T18:22:41.033Z"}
(node:356) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-23T18_22_41_852Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.

**Comment by MaxWinterstein** [comment]
This seems more and more confusing to me. There is also some discusson about that on the home assistant community and here: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/35

will have some tests and see if i can find something...

**Comment by MaxWinterstein** [comment]
is this still a thing?

**Comment by skank01** [comment]
no, you can close it

**Comment by skank01** [comment]
closed
