### ISSUE TITLE
Angry IP Scanner does not start

### ISSUE THREAD

**Issue by user45876** [MaxWinterstein/homeassistant-addons#101]
HA 2022.6.7 as HA OS Installation on Intel x86

After cleanly installing the Angry IP Scanner addon from the addon store, it can not be started. This is in the log:

`
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nginx.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/nginx.sh: Permission denied
cont-init: info: /etc/cont-init.d/nginx.sh exited 126
cont-init: info: running /etc/cont-init.d/novnc.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/novnc.sh: Permission denied
cont-init: info: /etc/cont-init.d/novnc.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by MaxWinterstein** [comment]
Is this a 32bit installation?

**Comment by user45876** [comment]
No 32 bit install, it is a standard x86-64 ha os install:

`# uname -a
Linux homeassistant 5.15.52 #1 SMP Thu Jul 7 15:15:30 UTC 2022 x86_64 HAOS
#`

**Comment by MaxWinterstein** [comment]
mhm, cant really reproduce :(

Tried using dev containers on my macbook but had no issue.

![image](https://user-images.githubusercontent.com/5927148/178668615-ecaca029-9d80-4ef3-a437-ca3fc4b9f756.png)


Might give me some more information? What hardware are you using? Can you show me a screenshot of `/config/system_health`?

**Comment by user45876** [comment]
Of course, Max, I am glad that you are having a look. I copied it from system health 'for github' and this is the output - how great is that 🥳

Hardware is a Dell 7040M, i5-6500T, 16GB RAM, 256GB SSD.

## System Health

version | core-2022.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.52
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4791
Installed Version | 1.26.0
Stage | running
Available Repositories | 1141
Downloaded Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 5. August 2022, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 234.0 GB
disk_used | 22.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2022.3.1), InfluxDB (4.5.0), Grafana (7.6.0), Network UPS Tools (0.11.0), Home Assistant Google Drive Backup (0.108.2), File editor (5.3.3), Mosquitto broker (6.1.2), TasmoAdmin (0.20.0), Z-Wave JS to MQTT (0.44.0), SSH & Web Terminal (11.0.1), chrony (2.4.0), MariaDB (2.5.0), phpMyAdmin (0.8.0), Log Viewer (0.14.0), RaspberryMatic CCU (3.63.9.20220625), Angry IP Scanner (0.1.0), AdGuard Home (4.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 18
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12. Juni 2022, 21:06
-- | --
current_recorder_run | 12. Juli 2022, 08:54
estimated_db_size | 2592.73 MiB
database_engine | mysql
database_version | 10.6.8

</details>

**Comment by user45876** [comment]
Max, I also tried pulling the log from the container,  it unsurprisingly it is just the same as the one above.

Do you know of a way to access the in container log of a crashed container?

`# docker logs 95faf516d656
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nginx.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/nginx.sh: Permission denied
cont-init: info: /etc/cont-init.d/nginx.sh exited 126
cont-init: info: running /etc/cont-init.d/novnc.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/novnc.sh: Permission denied
cont-init: info: /etc/cont-init.d/novnc.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
#`

**Comment by etimuh** [comment]
I've got exactly  the same  error.  Also x86-64 ha os, different hardware and core version

<html>
<body>


Version | core-2022.6.2
-- | --
Installation type | Home Assistant OS
Development version | false
Supervisor | true
Docker | true
User | root
Virtual environment | false
Python version | 3.9.12
Operating system family | Linux
The version of the operating system | 5.15.45
CPU architecture | x86_64
Time zone | Europe/Warsaw


</body>
</html>

**Comment by williamhelle** [comment]
Nothing new on this bug ? I got too

**Comment by user45876** [comment]
Nope - for me also, on the current 2022.9.6.

**Comment by williamhelle** [comment]
Got same problem :

nginx.sh: Permission denied
```
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/nginx.sh: Permission denied
```

Maybe require the nginx addon to be started before ? But this addon make my home assistant instance glitchy and buggy so don't want to test 😂

**Comment by MaxWinterstein** [comment]
So, this took me a while, as prio was not that high to be honest ;)

I did some rework on the image build process and now it works fine for me on my synology - a x86 arch:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/5927148/205379308-b013d94c-1604-4b92-8a9f-b3a1365360dc.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/5927148/205379407-5aad47ba-af4d-4c52-83fb-b4fd426005fb.png">

@williamhelle / @user45876  / @etimuh -- Might give it a new try? :)

**Comment by user45876** [comment]
Thanks a lot, Max, working perfectly now. Thanks for taking the time ☺️
