### ISSUE TITLE
ADS-B Multi-Portal Feeder: [reader][e]Could not connect to tcp://127.0.0.1:30005

### ISSUE THREAD

**Issue by flo269** [MaxWinterstein/homeassistant-addons#108]
Hi,

this plugin sounds wonderful, but I'm having problems getting it to run.
The reader somehow can't connect. Also, I can't connect to http://IP:8754.

To me (not knowing anything about the workings of this plugin) it seems like it might be a port problem? This is the output of docker ps:

> CONTAINER ID   IMAGE   COMMAND   CREATED   STATUS  PORTS NAMES
> 5d2a7xxxxxxx   aarch64-addon-adsb-multi-portal-feeder:1.17.0          "/init"   24 minutes ago      Up 24 minutes      8080/tcp, 8754/tcp, 30001-30005/tcp, 30104/tcp

Do you maybe have a hint, what I'm doing wrong? :-)

Let me know if you need any more info. Thank you!

This is my Config:
> SERVICE_ENABLE_DUMP1090: false
> SERVICE_ENABLE_PIAWARE: false
> SERVICE_ENABLE_FR24FEED: true
> SERVICE_ENABLE_HTTP: false
> PIAWARE_FEEDER_DASH_ID: ""
> FR24FEED_FR24KEY: REDACTED
> ADSBEXCHANGE_UUID: ""
> PLANEFINDER_SHARECODE: ""
> HTML_SITE_LAT: HOMEASSISTANT_LATITUDE
> HTML_SITE_LON: HOMEASSISTANT_LONGITUDE
> HTML_DEFAULT_TRACKER: Flightradar24

And this is the output of the logs. The warnings about not being able to connect keep repeating:

> s6-rc: info: service legacy-cont-init successfully started
> 
> s6-rc: info: service confd-html successfully started
> s6-rc: info: service init-upintheair successfully started
> s6-rc: info: service conf-adsbexchange successfully started
> s6-rc: info: service adsbexchange-feed: starting
> s6-rc: info: service confd-layers successfully started
> s6-rc: info: service http: starting
> s6-rc: info: service adsbexchange-feed successfully started
> s6-rc: info: service adsbexchange-stats: starting
> s6-rc: info: service adsbexchange-mlat: starting
> 2022-09-07T14:10:58+02:00 1e08b8fb-adsb-multi-portal-feeder /opt/confd/bin/confd[377]: INFO Backend set to env
> 2022-09-07T14:10:58+02:00 1e08b8fb-adsb-multi-portal-feeder /opt/confd/bin/confd[377]: INFO Starting confd
> 2022-09-07T14:10:58+02:00 1e08b8fb-adsb-multi-portal-feeder /opt/confd/bin/confd[377]: INFO Backend source(s) set to
> 2022-09-07T14:10:58+02:00 1e08b8fb-adsb-multi-portal-feeder /opt/confd/bin/confd[377]: INFO Target config /etc/fr24feed.ini out of sync
> 2022-09-07T14:10:58+02:00 1e08b8fb-adsb-multi-portal-feeder /opt/confd/bin/confd[377]: INFO Target config /etc/fr24feed.ini has been updated
> s6-rc: info: service adsbexchange-stats successfully started
> s6-rc: info: service adsbexchange-mlat successfully started
> s6-rc: info: service confd-fr24feed successfully started
> s6-rc: info: service fr24feed: starting
> s6-rc: info: service http successfully started
> s6-rc: info: service fr24feed successfully started
>  Add-on: ADS-B Multi-Portal Feeder
> s6-rc: info: service conf-planefinder successfully started
> s6-rc: info: service planefinder: starting
> s6-rc: info: service confd-piaware successfully started
> s6-rc: info: service piaware: starting
> s6-rc: info: service planefinder successfully started
> s6-rc: info: service planefinder-log: starting
> s6-rc: info: service piaware successfully started
> s6-rc: info: service planefinder-log successfully started
>  Dump1090 based feeder for FlightRadar24, FlightAware and more
> 
>  Add-on version: 1.17.0
>  You are running the latest version of this add-on.
> [fr24feed] 2022-09-07 14:11:02 | error | Local time: 2022-09-07 14:11:02 +0200
> [fr24feed] 2022-09-07 14:11:02 | error | GMT+0 time: 2022-09-07 13:11:02 +0200
> [fr24feed] 2022-09-07 14:11:02 | error | Your machine should be set as GMT+0 time zone!
> [fr24feed] 2022-09-07 14:11:02 | warning | Time zone is not set to GMT+0
>
> [fr24feed] 2022-09-07 14:11:02 | [main][i]FR24 Feeder/Decoder
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Version: 1.0.25-3/generic
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Built on Apr  8 2020 07:06:55 (HEAD-5e8ef0c.git/Linux/static_armel)
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Running on: debian11
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Local IP(s): 172.xx.xx.0
>
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Copyright 2012-2020 Flightradar24 AB
> [fr24feed] 2022-09-07 14:11:02 | [main][i]https://www.flightradar24.com
> [fr24feed] 2022-09-07 14:11:02 | [main][i]DNS mode: PING
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Automatic updates are DISABLED
> [fr24feed] 2022-09-07 14:11:02 | info | [httpd]Server started, listening on 0.0.0.0:8754
> [fr24feed] 2022-09-07 14:11:02 | [i]PacketSenderConfiguration::fetch_config(): Yoda configuration for this receiver is disabled
> [fr24feed] 2022-09-07 14:11:02 | [d]TLSConnection::ctor(): Enable verify_peer in production code!
> [fr24feed] 2022-09-07 14:11:02 | [main][i]Reader thread started
> [fr24feed] 2022-09-07 14:11:02 | [main][i]MLAT data feed started
> [fr24feed] 2022-09-07 14:11:02 | [mlat][i]Waiting for MLAT configuration
> [fr24feed] 2022-09-07 14:11:02 | [reader][i]Initializing reader
> [fr24feed] 2022-09-07 14:11:02 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> **[fr24feed] 2022-09-07 14:11:02 | [reader][e]Could not connect to tcp://127.0.0.1:30005**
> [fr24feed] 2022-09-07 14:11:02 | [master][i]Starting processing thread
>  System: Home Assistant OS 8.5  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2022.8.7
> 
>  Home Assistant Supervisor: 2022.08.5
> 
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> 
> s6-rc: info: service banner successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [fr24feed] 2022-09-07 14:11:03 | [time][i]Synchronizing time via NTP
> [fr24feed] 2022-09-07 14:11:04 | [time][i]Time synchronized correctly, offset -0.001 seconds
> [fr24feed] 2022-09-07 14:11:04 | [feed][i]Downloading configuration
> [fr24feed] 2022-09-07 14:11:04 | [main][i]Feed Network client started
> [fr24feed] 2022-09-07 14:11:04 | [feed][d]fetching configuration
> [fr24feed] 2022-09-07 14:11:04 | [feed][i]configuring decoder
> [fr24feed] 2022-09-07 14:11:04 | [feed][c]Max range AIR: 350.0nm
> [fr24feed] 2022-09-07 14:11:04 | [feed][c]Max range GND: 100.0nm
> [fr24feed] 2022-09-07 14:11:04 | [feed][i]configuration changed
> [fr24feed] 2022-09-07 14:11:04 | [feed][i]defined 3 servers
> [fr24feed] 2022-09-07 14:11:04 | info | [stats]Stats thread started
> [fr24feed] 2022-09-07 14:11:04 | [feed][c]Timestamps: optional
> [fr24feed] 2022-09-07 14:11:04 | info | Stopping ReceiverACSender threads for feed 
> [fr24feed] 2022-09-07 14:11:04 | info | Configured ReceiverACSender: REDACTED:8099,REDACTED:8099,REDACTED:8099, feed: REDACTED, send_interval: 5s, max age: 15s, send metadata: true, mode: 1, filtering: true
> [fr24feed] 2022-09-07 14:11:04 | info | Network thread connecting to REDACTED for feed REDACTED
> [fr24feed] 2022-09-07 14:11:04 | [feed][n]REDACTED@REDACTED:8099/UDP
> [fr24feed] 2022-09-07 14:11:04 | [feed][n]connecting
> [fr24feed] 2022-09-07 14:11:04 | [feed][n]connected via UDP (fd 29)
> [fr24feed] 2022-09-07 14:11:04 | [feed][i]Feed connected
> [fr24feed] 2022-09-07 14:11:04 | [feed][n]working
> **[fr24feed] 2022-09-07 14:11:07 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:07 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:12 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:12 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:17 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:17 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:22 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:22 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:27 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:27 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:32 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
> [fr24feed] 2022-09-07 14:11:32 | [reader][e]Could not connect to tcp://127.0.0.1:30005
> [fr24feed] 2022-09-07 14:11:34 | [feed][n]ping 1**

**Comment by flo269** [comment]
Yes I did. I thought this would only be needed to dump to another service running locally.
Do you think it might help to just activate it?

**Comment by MaxWinterstein** [comment]
Yeah, give it a try
