### ISSUE TITLE
FlightRadar24 KEY retrieve information request

### ISSUE THREAD

**Issue by pstoian** [MaxWinterstein/homeassistant-addons#112]
Hi - 

How can I get the key for FlightRadar24 ?! I tried some online instructions but without any success. Also followed the add-on instructions - and I am able to get only the hostname / FlightAware ID - but not the Flightradar24 Key.

Your assistance is appreciated.

Thank you.

My logs are here below:
-----------------------------------------------------------
[fr24feed] 2022-10-28 10:59:34 | ______  _  _         _      _                    _              _____    ___ 
[fr24feed] 2022-10-28 10:59:34 | |  ___|| |(_)       | |    | |                  | |            / __  \  /   |
[fr24feed] 2022-10-28 10:59:34 | | |_   | | _   __ _ | |__  | |_  _ __  __ _   __| |  __ _  _ __`' / /' / /| |
[fr24feed] 2022-10-28 10:59:34 | |  _|  | || | / _` || '_ \ | __|| '__|/ _` | / _` | / _` || '__| / /  / /_| |
[fr24feed] 2022-10-28 10:59:34 | | |    | || || (_| || | | || |_ | |  | (_| || (_| || (_| || |  ./ /___\___  |
[fr24feed] 2022-10-28 10:59:34 | \_|    |_||_| \__, ||_| |_| \__||_|   \__,_| \__,_| \__,_||_|  \_____/    |_/
[fr24feed] 2022-10-28 10:59:34 |                __/ |                                                         
[fr24feed] 2022-10-28 10:59:34 |               |___/                                                          
[fr24feed] 2022-10-28 10:59:34 | [main][i]FR24 Feeder/Decoder
[fr24feed] 2022-10-28 10:59:34 | [main][i]Version: 1.0.25-3/generic
[fr24feed] 2022-10-28 10:59:34 | [main][i]Built on Apr  8 2020 07:06:55 (HEAD-5e8ef0c.git/Linux/static_armel)
[fr24feed] 2022-10-28 10:59:34 | error | Local time: 2022-10-28 10:59:34 -0500
[fr24feed] 2022-10-28 10:59:34 | error | GMT+0 time: 2022-10-28 16:59:34 -0500
[fr24feed] 2022-10-28 10:59:34 | error | Your machine should be set as GMT+0 time zone!
[fr24feed] 2022-10-28 10:59:34 | [main][i]Running on: debian11
[fr24feed] 2022-10-28 10:59:34 | [main][i]Local IP(s): 172.30.33.8
[fr24feed] 2022-10-28 10:59:34 | [main][i]Copyright 2012-2020 Flightradar24 AB
[fr24feed] 2022-10-28 10:59:34 | [main][i]https://www.flightradar24.com
[fr24feed] 2022-10-28 10:59:34 | [main][i]DNS mode: PING
[fr24feed] 2022-10-28 10:59:34 | warning | Time zone is not set to GMT+0
[fr24feed] 2022-10-28 10:59:34 | [main][i]Automatic updates are DISABLED
[fr24feed] 2022-10-28 10:59:34 | info | [httpd]Server started, listening on 0.0.0.0:8754
[fr24feed] 2022-10-28 10:59:34 | [i]PacketSenderConfiguration::fetch_config(): Yoda configuration for this receiver is disabled
[fr24feed] 2022-10-28 10:59:35 | [d]TLSConnection::ctor(): Enable verify_peer in production code!
[fr24feed] 2022-10-28 10:59:35 | [main][i]Reader thread started
[fr24feed] 2022-10-28 10:59:35 | [main][i]MLAT data feed started
[fr24feed] 2022-10-28 10:59:35 | [mlat][i]Waiting for MLAT configuration
[fr24feed] 2022-10-28 10:59:35 | [master][i]Starting processing thread
 Add-on version: 1.17.0
[fr24feed] 2022-10-28 10:59:35 | [reader][i]Initializing reader
[fr24feed] 2022-10-28 10:59:35 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
[fr24feed] 2022-10-28 10:59:35 | [reader][i]Connected to the receiver, configuring
[fr24feed] 2022-10-28 10:59:35 | [reader][i]Configured, processing messages
[piaware] warning: /etc/piaware.conf:7: invalid value for option feeder-id: f1c878cb-adsb-multi-portal-feeder
[piaware] ****************************************************
[piaware] piaware version 7.2 is running, process ID 442
[piaware] your system info is: Linux f1c878cb-adsb-multi-portal-feeder 5.15.74 #1 SMP PREEMPT Thu Oct 20 22:58:53 UTC 2022 aarch64 GNU/Linux
 You are running the latest version of this add-on.
[fr24feed] 2022-10-28 10:59:35 | [reader][i]Timestamp source changed from UNKNOWN to SYSTEM-UNCERTAIN
 System: Home Assistant OS 9.3  (aarch64 / odroid-n2)
[fr24feed] 2022-10-28 10:59:36 | [time][i]Synchronizing time via NTP
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[piaware] Connecting to FlightAware adept server at piaware.flightaware.com/1200
[piaware] Connection with adept server at piaware.flightaware.com/1200 established
[piaware] TLS handshake with adept server at piaware.flightaware.com/1200 completed
[piaware] FlightAware server certificate validated
[piaware] encrypted session established with FlightAware
[piaware] warning: /etc/piaware.conf:7: invalid value for option feeder-id: f1c878cb-adsb-multi-portal-feeder
[piaware] logged in to FlightAware as user guest
[piaware] my feeder ID is 11e45958-b436-48ee-8aae-4e054d8e429d
[piaware] ADS-B data program 'dump1090' is listening on port 30005, so far so good
[piaware] Starting faup1090: /usr/lib/piaware/helpers/faup1090 --net-bo-ipaddr 127.0.0.1 --net-bo-port 30005 --stdout
[piaware] Started faup1090 (pid 527) to connect to dump1090
[piaware] UAT support disabled by local configuration setting: uat-receiver-type
[fr24feed] 2022-10-28 10:59:38 | [time][i]Time synchronized correctly, offset -0.001 seconds
[fr24feed] 2022-10-28 10:59:38 | [main][i]Feed Network client started
[fr24feed] 2022-10-28 10:59:38 | [feed][i]Downloading configuration
[fr24feed] 2022-10-28 10:59:38 | [feed][d]fetching configuration
[fr24feed] 2022-10-28 10:59:38 | [feed][e]failure: Database error!
[fr24feed] 2022-10-28 10:59:38 | [feed][i]Failed on start, Sleeping 120 seconds
[fr24feed] 2022-10-28 10:59:38 | [reader][i]Timestamp source changed from SYSTEM-UNCERTAIN to SYSTEM-VALIDATED
[piaware] piaware received a message from dump1090!

**Comment by MaxWinterstein** [comment]
Obtaining the key is not really implemented in the Add-on. 

The easiest way might still be to just run a local docker container:
```bash
docker run -it --rm \
        -e "SERVICE_ENABLE_DUMP1090=false" \
        -e "SERVICE_ENABLE_HTTP=false" \
        -e "SERVICE_ENABLE_PIAWARE=false" \
        -e "SERVICE_ENABLE_FR24FEED=false" \
        thomx/fr24feed-piaware /bin/bash
``` 
and within run `/fr24feed/fr24feed/fr24feed --signup`  and follow the instructions, for technical steps, your answer doesn't matter we just need the sharing key at the end. 

(stolen from https://github.com/Thom-x/docker-fr24feed-piaware-dump1090#flightradar24)

**Comment by pstoian** [comment]
Thank you for your response. 

So, what you mean is to run a local docker container - instead of the HA add-on ?! I love the Add-on as is integrated into the HA and no other maintenance to other hardware is need it.  And there is no way to get the key out of the HA Terminal line ?

**Comment by MaxWinterstein** [comment]
> So, what you mean is to run a local docker container - instead of the HA add-on ?! 

Just for the purpose of generating the key. After that you can let the add-on handle all the work.

> And there is no way to get the key out of the HA Terminal line ?

I am not that familiar with the HA Terminal. If you can access your home assistant instance via SSH it would be a piece of cake.

**Comment by MaxWinterstein** [comment]
Did you manage to get it working @pstoian ?
