### ISSUE TITLE
[CUPS] mDNS is not working, e.g. shared printers are not announced via Bonjour

### ISSUE THREAD

**Issue by MaxWinterstein** [MaxWinterstein/homeassistant-addons#128]
Currently, the mDNS is not working. I guess it's somehow supposed to forward its announcements to some HA pod to do its job, but currently, it won't. 

The only way I got it working for now is by using `host_network: true` - which works but produces warnings about an already existing mDNS installation.

any help is welcome.

**Comment by johnboiles** [comment]
[Here's a solution](https://community.home-assistant.io/t/implementing-mdns-into-custom-addon/277993/3), but it seems to require PyScript from HACS so it's not ideal. I wonder how this works under the hood. Is there a `dbus`-y way to talk to the host system and register a new port? Don't addons have access to the host dbus?

**Comment by johnboiles** [comment]
Looks like addons _can_ have access to the host dbus: https://developers.home-assistant.io/docs/add-ons/configuration#add-on-configuration

**Comment by MaxWinterstein** [comment]
As the newest add-on version seems to do the job, I am going to close this here.

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/5927148/46581cde-15ac-4c0c-8b02-31b66ca610fe)
