### ISSUE TITLE
option to select USB device

### ISSUE THREAD

**Issue by Rothammel** [MaxWinterstein/homeassistant-addons#134]
I have two rtl devices, one for my 433MHz temperature sensors, and one for ADS-B Multi-Portal Feeder

**Comment by MaxWinterstein** [comment]
I don't think I can reproduce this here for myself, as I don't have access to multiple devices. 

But I guess you can provide an argument towards dump1090 that selects the device. See 
https://github.com/antirez/dump1090/issues/129#issuecomment-406278136

**Comment by MaxWinterstein** [comment]
Providing dump1090 args can be archived using this field:

![image](https://user-images.githubusercontent.com/5927148/215416278-09eab305-a1b8-4348-91f2-b99ea82d28e7.png)

**Comment by Rothammel** [comment]
Awesome, it works. thank you so much
