### ISSUE TITLE
FR24 Version 

### ISSUE THREAD

**Issue by sondi2003** [MaxWinterstein/homeassistant-addons#135]
Hallo,
Ich habe diese Info heute von FR24 erhalten. Wann kann ich mit einem Update rechnen? Wird dies behoben?

Dear Host,

We have noticed that you are using an older version of Flightradar24 data sharing software (1.0.25-3) that we are phasing out. We would therefore like you to upgrade to the latest version (1.0.34-0) before Feb 28, 2023.

Danke
Sondi2003

**Comment by yousaf465** [comment]
Dear Host,We have noticed that you are using an older version of Flightradar24 data sharing software (1.0.25-3) that we are phasing out. We would therefore like you to upgrade to the latest version (1.0.34-0) before Feb 28, 2023.Follow the procedure given below to upgrade:SSH into your pi and login to it.Run the following commands - one at a time:sudo chmod +x /usr/lib/fr24/fr24feed_updater.shsudo /usr/lib/fr24/fr24feed_updater.shIf you don’t know how to SSH, check this article. Make sure you have auto updates enabled.

**Comment by sondi2003** [comment]
Hallo,
vielen dank für das schnelle Feedback. Habe nicht gewusst dass dies auch für die HomeAssistant integration gilt.

Danke
Gruss
Sondi2003

**Comment by MaxWinterstein** [comment]
Currently the maintainer of the base image behind this addon are working on an update:  
https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/106  
When this is done, I can prepare an update of the addon.

I am sure this will be before 28th February ;)

---

@sondi2003  das wird dir nicht wirklich weiterhelfen. Warte einfach ein wenig und dann wird es auch ein Update für das AddOn geben.

Gruß

**Comment by MaxWinterstein** [comment]
Update is available ✌️

**Comment by sondi2003** [comment]
greeat Thank You!Freundliche Grüsse Richard Sonderegger Am 20.01.2023 um 22:31 schrieb Max Winterstein ***@***.***>:﻿
Update is available ✌️
