### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by lead0r** [MaxWinterstein/homeassistant-addons#142]
I added your repository succesfully using the "add repository to my home assistant" button, but it does not show up in the add-on store. 

Log error:

23-02-10 13:37:09 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/MaxWinterstein/homeassistant-addons/tree/main/cups repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/MaxWinterstein/homeassistant-addons/tree/main/cups /data/addons/git/efdc53f9
  stderr: 'Cloning into '/data/addons/git/efdc53f9'...
fatal: repository 'https://github.com/MaxWinterstein/homeassistant-addons/tree/main/cups/' not found
'.
23-02-10 13:37:09 ERROR (MainThread) [supervisor.store] Can't retrieve data from https://github.com/MaxWinterstein/homeassistant-addons/tree/main/cups due to 

(that's were it ends, the sentence is cut of)

When I test a local "git pull https://github.com/MaxWinterstein/homeassistant-addons/tree/main/cups" I get a similar error

**Comment by lead0r** [comment]
Now it worked, no idea why

**Comment by MaxWinterstein** [comment]
I am glad to hear that 👍 

I was confuseda about the `/cups` part in the URL, but can't explain where it was from.
