### ISSUE TITLE
[CUPS] Access restricted from a specific IP

### ISSUE THREAD

**Issue by hcura-qa** [MaxWinterstein/homeassistant-addons#143]
Right after the first printer has been added, when trying to access as admin, the following error is shown:
![image](https://user-images.githubusercontent.com/79648600/222989564-444ad920-ac03-48a3-a079-33e129f00f32.png)

Looks like the access is restricted to be made from a specific IP. No sure if that IP address is from the docker container that runs Hassio, but in this case maybe the access can be open for all IPs.

**Comment by davidjirovec** [comment]
Are you using ssl? Try to disable both ssl and require_ssl in addon configuration.

**Comment by MaxWinterstein** [comment]
Not happening in the new add-on implementation
