### ISSUE TITLE
OctoPrint Proxy

### ISSUE THREAD

**Issue by kevorm** [MaxWinterstein/homeassistant-addons#146]
I am using OctoprintProxy 1.0.2 and
 Home Assistant 2023.3.6 Supervisor 2023.03.3 Operating System 9.5 Frontend 20230309.1 - latest 

I have website embedding enabled in OctoPrint and in HA i have my proxy setup like 
octoprint_host: 10.0.0.90
octoprint_port: "443"
ssl:
  enabled: true
  verify: false

I am using https to connect to HA.

in octoprint i have 
accessControl:
  autologinAs: admin
  autologinLocal: true
  localNetworks:
  - 127.0.0.0./8
  - 10.0.0.0/8
  - 192.168.0.0/16
  
  I get 
  Passive login failed. Please check your [browser's error console](https://faq.octoprint.org/browser-console) and [octoprint.log](https://faq.octoprint.org/logs) for possible reasons.Also make sure that the server is actually running by reloading this page.
  
  What am I missing?

**Comment by MaxWinterstein** [comment]
Can't really help on this. But i guess it's the same issue as https://github.com/MaxWinterstein/homeassistant-addons/issues/115 - so lets close this here and continue in one issue
