### ISSUE TITLE
ADS-B Feeder | High CPU Usage on Home Assistant OS 10

### ISSUE THREAD

**Issue by MaxWinterstein** [MaxWinterstein/homeassistant-addons#151]
Anybody experiencing unusually high CPU usage with this Addon since OS V10? It usually sat at ~3% and now it idles with 20% with the addon enabled.

Edit:
![Bildschirmfoto vom 2023-04-21 10-50-22](https://user-images.githubusercontent.com/613272/233593991-f1b52433-051a-4d89-99de-353aa9dd8e17.png)

_Originally posted by @maweki in https://github.com/MaxWinterstein/homeassistant-addons/issues/149#issuecomment-1517484880_

**Comment by therealhalifax** [comment]
Same issue for me. First I made the update of the Addon to x.3 and after the update of the OS to 10.0. The CPU load increased from normaly 3% to 26%. If I restart the Addon the CPU load goes down to 1-2% for about 30s and than switch back to 26%

**Comment by MaxWinterstein** [comment]
Out of curiosity, does this also happen when disabling the http server?

**Comment by maweki** [comment]
> Out of curiosity, does this also happen when disabling the http server?

The FR24 feeder service seems to be the issue. Deactivating that drops the CPU usage.

**Comment by Tntdruid** [comment]
My HA looks like this whit addon running:
![firefox_2023-04-21_15-31-17](https://user-images.githubusercontent.com/72948/233648858-b32214bb-a8d9-420e-a4b9-5dfe8a226706.png)

From proxmox VM

**Comment by lopeti** [comment]
Same issue for me.

**Comment by mrkaqz** [comment]
> > Out of curiosity, does this also happen when disabling the http server?
> 
> The FR24 feeder service seems to be the issue. Deactivating that drops the CPU usage.

Yes after disable FR24 Feed. The cpu came back to normal. Seem like it cause the issue.

**Comment by chiefcomm** [comment]
Any progress on this issue, higher than normal CPU isn't a concern but with higher CPU comes higher CPU temps which concern me somewhat, nothing unmanageable yet but then for me it is in the cooler months so would prefer to have some idea as to when we could see a fix :-(

![image](https://user-images.githubusercontent.com/45157523/234775189-a26eeafc-30c2-4bfb-8a9d-08b24df5e76d.png)

**Comment by mrkaqz** [comment]
> Any progress on this issue, higher than normal CPU isn't a concern but with higher CPU comes higher CPU temps which concern me somewhat, nothing unmanageable yet but then for me it is in the cooler months so would prefer to have some idea as to when we could see a fix :-(
> 
> ![image](https://user-images.githubusercontent.com/45157523/234775189-a26eeafc-30c2-4bfb-8a9d-08b24df5e76d.png)

I am waiting for a fix also, i am on a programmer so I can only help test but not fix. I have disable FR24feed for a moment waiting for a fix. If it taking longer I will have to fire up another VM just to run it out from the HA but if anyone can help fix this issue i will be much happy :)

**Comment by mrkaqz** [comment]
with version [1.21.0] - 2023-04-27 updated this morning, still not fix high CPU issue. 

![image](https://user-images.githubusercontent.com/6989907/235070366-79293451-cc42-43bb-8c43-6f745f38f359.png)

**Comment by MaxWinterstein** [comment]
yeah, the update was not really ment to fix the cpu issue. 

For the moment I am not sure what happens there. FR24feed was updated along `v1.19.0` - that was a few weeks ago. I hope to reproduce this by playing with the `ulimit` stuff that changed along docker `v23`, but need to find some time for that.

**Comment by Tntdruid** [comment]
The latest update crash my HA whit oom, had to role back to 1.20.3

**Comment by mrkaqz** [comment]
> 

I am waiting for a fix as well :)

**Comment by SenMorgan** [comment]
Me too waiting for fix

**Comment by MaxWinterstein** [comment]
I just updated my OrangePi5 to docker v23, but I am having a hard time to replicate this.

Running with FR24:

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/5927148/7f5895aa-07a0-455e-87cc-fae67cdcedd7)

Running without:

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/5927148/a8632726-c2fb-4eb5-ade3-3ec2a6158e48)

@mrkaqz What sensor are you looking at? Where is the information from?

**Comment by mrkaqz** [comment]
I can see it from the add-on info page.

Here is with FR24 disable the CPU usage is about 1%

![Screenshot_20230513-162658](https://github.com/MaxWinterstein/homeassistant-addons/assets/6989907/18338a33-ba18-4586-b760-7807302e81d4)

Then once FR24 is enable, the usage went up to 30%

![Screenshot_20230513-162745](https://github.com/MaxWinterstein/homeassistant-addons/assets/6989907/653a631b-9883-4ad6-8a23-9a0e6b969275)

**Comment by Delta1977** [comment]
this is on may Intel i7 HA Maschine when Feeder runs. I hear the fan on 100 %:
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/1581154/4709fe6e-1ba5-434d-9594-ebf20c7ab8af)

**Comment by maweki** [comment]
Logging into the ha-os container with `docker exec` I find the fr24feed binary to cause huge cpu spikes.

![grafik](https://github.com/MaxWinterstein/homeassistant-addons/assets/613272/904f3c21-ef51-4930-916c-537c6b356046)

I started the feder service under `strace` and the high cpu usage starts when this happens:

```
ugetrlimit(RLIMIT_NOFILE, {rlim_cur=1073741816, rlim_max=1073741816}) = 0
fcntl64(0, F_GETFD)                     = 0
fcntl64(1, F_GETFD)                     = 0
fcntl64(2, F_GETFD)                     = 0
fcntl64(3, F_GETFD)                     = 0
fcntl64(4, F_GETFD)                     = 0
fcntl64(5, F_GETFD)                     = 0
fcntl64(6, F_GETFD)                     = 0
fcntl64(7, F_GETFD)                     = 0
fcntl64(8, F_GETFD)                     = 0
fcntl64(9, F_GETFD)                     = -1 EBADF (Bad file descriptor)
fcntl64(10, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(11, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(12, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(13, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(14, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(15, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(16, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(17, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(18, F_GETFD)                    = -1 EBADF (Bad file descriptor)
fcntl64(19, F_GETFD)                    = -1 EBADF (Bad file descriptor)
...
```

which looks to me like iterating over the file system maybe, but I'm not a systems programmer. With `strace` it takes so long and I've not reached the end yet. Without `strace` the load drops after some time and then, after a few seconds it picks up again (I guess, starting the process anew).

If the feeder goes through all file descriptors, then maybe setting a low limit might help.

**Comment by maweki** [comment]
Okay, starting with ( ulimit -n 1024 && fr24feed ) works, as it only iterates up to 1024.

Therefore I propose the following "fix":

in `/etc/s6-overlay/s6-rc.d/fr24feed/run` (or wherever that actually is in all this container stuff)

change

```
if [ "$SERVICE_ENABLE_FR24FEED" != "false" ]; then
	set -eo pipefail
	/fr24feed/fr24feed/fr24feed 2>&1 | mawk -W interactive '{printf "%c[34m[fr24feed]%c[0m %s\n", 27, 27, $0}'
	# awk -W interactive ...  (prefix log messages with color and "[fr24feed]")
else
	tail -f /dev/null
fi
```

to

```
if [ "$SERVICE_ENABLE_FR24FEED" != "false" ]; then
	set -eo pipefail
	( ulimit -n 1024 && /fr24feed/fr24feed/fr24feed ) 2>&1 | mawk -W interactive '{printf "%c[34m[fr24feed]%c[0m %s\n", 27, 27, $0}'
	# awk -W interactive ...  (prefix log messages with color and "[fr24feed]")
else
	tail -f /dev/null
fi
```

**Comment by mblauth** [comment]
Very interesting. Did you try setting the ulimits via docker/podman (--ulimit option)? Maybe this would also do the trick without having to modify the scripts in the container.

**Comment by maweki** [comment]
I am not sure I can do that within the home assistant appliance.

The thing is, that the feeder binary seems to iterate over all possible file descriptors (for whatever reason). So imposing that limit from outside should work as well BUT it's then imposed on everything within the container (the webserver, the other feeder, etc.). Then 1024 might be too low a number.

**Comment by mblauth** [comment]
That makes perfect sense. I came from the sdr-enthusiasts/docker-flightradar24 project where you linked your post here, I am running the fr24 stuff in a separate container, hence my suggestion. I didn't realize it didn't fit in the context of this project.

**Comment by Delta1977** [comment]
In newest Image Thom-x exposes the Ulimit in Dockerfile. 
Maybe so its easier to configure the parameter in HA

https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/commit/36856fe8810c50ed1a280c86b0357965631c6e03

**Comment by maweki** [comment]
I wouldn't know where to start guessing a limit that is easy on the cpu (the lower the better, because all are iterated over) and a number that is large enough for all services included in the addon.

Seeing that 1024 seemed enough for fr24feed, the million-odd from the docker file could be overly large already.

It's CPU time and energy we could be cumulatively wasting here.

**Comment by mrkaqz** [comment]
> In newest Image Thom-x exposes the Ulimit in Dockerfile. Maybe so its easier to configure the parameter in HA
> 
> [Thom-x/docker-fr24feed-piaware-dump1090@36856fe](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/commit/36856fe8810c50ed1a280c86b0357965631c6e03)

@MaxWinterstein May you look at this please, the container is updated to version 1.23 now.
Not sure if we just updated the version will fix issue or may need to set  some other parameter. 

Finger cross.

Thanks

**Comment by Delta1977** [comment]
@MaxWinterstein Hey Max, are you still actively taking care of this repository? What is your plan for this issue? In my opinion, only the ENV needs to be set.

**Comment by MaxWinterstein** [comment]
It's kinda ugly that Thom-x sells this as a system setting, as in fact this only targets the thttp server process. 

Also I am confused why there is no issues with the fr24 feed in his repository, this should be an issue for him as well?!

**Comment by Delta1977** [comment]
Sorry, you are right. He sets ulimit in front of thttp start. So  all other process before starte with unlimited.

**Comment by maweki** [comment]
> Simply overwriting the original files is not a good style

It's not too too uncommon to package/provide a custom run-script. My proposal was not very invasive.

**Comment by MaxWinterstein** [comment]
> It's not too too uncommon to package/provide a custom run-script. My proposal was not very invasive.

Sure, don't get me wrong. It is just another thing on the list if things I have to remember to always double check when the upstream releases. And I am lazy :)

---

I just released an update that now contains two new settings:

- `ULIMIT_N` - used by the `thttp` server - default to the old default
- `FR24FEED_ULIMIT_N` - used by FR24Feed, just rolled the dice and choosed 1024

This should allow for testing for everyone with issues. 

Feedback is highly welcomed ❤️

**Comment by CoMPaTech** [comment]
Installing as we speak/type

**Comment by mrkaqz** [comment]
Updated and been running for hours, not seeing high CPU usage so far
with FR24FEED_ULIMIT_N
1024.

[image: image.png]

thanks a lot for the update.

**Comment by chiefcomm** [comment]
Lovely just lovely both CPU usage and CPU temp dropped back to normal with this update :-)

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/45157523/1b0baf79-d668-4433-98c0-e26592239cd9)
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/45157523/0fe785e0-867e-4d21-b30e-a1183abb1ac6)

**Comment by yousaf465** [comment]
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/83491212/ce87c94f-eb1d-451b-9b29-2e0d90481ecc)

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/83491212/a3418f94-6925-4b52-a3e4-8caf6c352441)

There is a clear difference now, even though I hadn't noticed an issue before.

**Comment by Delta1977** [comment]
Thanks for the patch. CPU wants down from 34 to 3 %.  I set both ulimit to 1024 which was iirc the default in docker < v23 ( Hassos < v19)

**Comment by therealhalifax** [comment]
Perfect Result even with default settings 🤗👍

**Comment by MaxWinterstein** [comment]
Alright, thanks for the ride everyone, it seems we have a solution figured out.

Thanks ❤️
