### ISSUE TITLE
s6-rc: info: service legacy-services: stopping

### ISSUE THREAD

**Issue by lead0r** [MaxWinterstein/homeassistant-addons#152]
The CUPS add-on worked for me for months and now it crashes. Since there has been no update, I reckon it is due to a HA OS / HA Supervisor Update?

This is the full log:

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/dbus-setup
> cont-init: info: /etc/cont-init.d/dbus-setup exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun avahi (no readiness notification)
> services-up: info: copying legacy longrun dbus (no readiness notification)
> services-up: info: copying legacy longrun nginx (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
> Successfully dropped root privileges.
> avahi-daemon 0.8 starting up.
> Successfully called chroot().
> Successfully dropped remaining capabilities.
> No service file found in /etc/avahi/services.
> Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.9.
> New relevant interface eth0.IPv4 for mDNS.
> Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
> New relevant interface lo.IPv4 for mDNS.
> Network interface enumeration completed.
> Server startup complete. Host name is homeassistant.local. Local service cookie is 3124669239.
> dbus-daemon[73]: [system] Activating service name='org.freedesktop.ColorManager' requested by ':1.1' (uid=0 pid=187 comm="/usr/sbin/cupsd -f ") (using servicehelper)
> dbus-daemon[73]: [system] Successfully activated service 'org.freedesktop.ColorManager'
> s6-rc: info: service legacy-services: stopping
> Got SIGTERM, quitting.
> Leaving mDNS multicast group on interface eth0.IPv4 with address 172.30.33.9.
> Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
> avahi-daemon 0.8 exiting.
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Changuitox** [comment]
Same problem here. Worked for month and now crash after HA OS and HA Supervisor Update.

Full log

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/dbus-setup
cont-init: info: /etc/cont-init.d/dbus-setup exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun avahi (no readiness notification)
services-up: info: copying legacy longrun dbus (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.5.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Server startup complete. Host name is Homeassistant.local. Local service cookie is 1253129812.
s6-rc: info: service legacy-services: stopping
Got SIGTERM, quitting.
Leaving mDNS multicast group on interface eth0.IPv4 with address 172.30.33.5.
Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
avahi-daemon 0.8 exiting.
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by Changuitox** [comment]
Hello @lead0r have you found any solution?  I still have the same problem

> The CUPS add-on worked for me for months and now it crashes. Since there has been no update, I reckon it is due to a HA OS / HA Supervisor Update?
> 
> This is the full log:
> 
> > s6-rc: info: service s6rc-oneshot-runner: starting
> > s6-rc: info: service s6rc-oneshot-runner successfully started
> > s6-rc: info: service fix-attrs: starting
> > s6-rc: info: service fix-attrs successfully started
> > s6-rc: info: service legacy-cont-init: starting
> > cont-init: info: running /etc/cont-init.d/dbus-setup
> > cont-init: info: /etc/cont-init.d/dbus-setup exited 0
> > s6-rc: info: service legacy-cont-init successfully started
> > s6-rc: info: service legacy-services: starting
> > services-up: info: copying legacy longrun avahi (no readiness notification)
> > services-up: info: copying legacy longrun dbus (no readiness notification)
> > services-up: info: copying legacy longrun nginx (no readiness notification)
> > s6-rc: info: service legacy-services successfully started
> > Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
> > Successfully dropped root privileges.
> > avahi-daemon 0.8 starting up.
> > Successfully called chroot().
> > Successfully dropped remaining capabilities.
> > No service file found in /etc/avahi/services.
> > Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.9.
> > New relevant interface eth0.IPv4 for mDNS.
> > Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
> > New relevant interface lo.IPv4 for mDNS.
> > Network interface enumeration completed.
> > Server startup complete. Host name is homeassistant.local. Local service cookie is 3124669239.
> > dbus-daemon[73]: [system] Activating service name='org.freedesktop.ColorManager' requested by ':1.1' (uid=0 pid=187 comm="/usr/sbin/cupsd -f ") (using servicehelper)
> > dbus-daemon[73]: [system] Successfully activated service 'org.freedesktop.ColorManager'
> > s6-rc: info: service legacy-services: stopping
> > Got SIGTERM, quitting.
> > Leaving mDNS multicast group on interface eth0.IPv4 with address 172.30.33.9.
> > Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
> > avahi-daemon 0.8 exiting.
> > s6-rc: info: service legacy-services successfully stopped
> > s6-rc: info: service legacy-cont-init: stopping
> > s6-rc: info: service legacy-cont-init successfully stopped
> > s6-rc: info: service fix-attrs: stopping
> > s6-rc: info: service fix-attrs successfully stopped
> > s6-rc: info: service s6rc-oneshot-runner: stopping
> > s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by jstch** [comment]
I'm facing the same issue. Did anyone found a solution? 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/dbus-setup
cont-init: info: /etc/cont-init.d/dbus-setup exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun avahi (no readiness notification)
services-up: info: copying legacy longrun dbus (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.6.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Server startup complete. Host name is homeassistant.local. Local service cookie is 665544898.
s6-rc: info: service legacy-services: stopping
Disconnected from D-Bus, exiting.
Got SIGTERM, quitting.
Leaving mDNS multicast group on interface eth0.IPv4 with address 172.30.33.6.
Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
avahi-daemon 0.8 exiting.
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by lead0r** [comment]
@Changuitox No, I don't have a solution

**Comment by jflecool2** [comment]
Hello,
Also had the issue with HA Os 10.1 (supervisor 2023.4.1 ha 2023.4.6). This ain't Apple so I just downgraded HA OS with the following command and cups is working again (didn't touch HA or Supervisor) :
`ha os update --version 9.5`

**Comment by Changuitox** [comment]
@jflecool2 thanks a lot, that help me to fix My cups server. Working again.

**Comment by lead0r** [comment]
> Hello,
> Also had the issue with HA Os 10.1 (supervisor 2023.4.1 ha 2023.4.6). This ain't Apple so I just downgraded HA OS with the following command and cups is working again (didn't touch HA or Supervisor) :
> `ha os update --version 9.5`

Okay. That narrowed down the problem, but it's not really a permanent solution

**Comment by orrpan** [comment]
Any news on the real problem?

**Comment by Changuitox** [comment]
No solution yet, im still on version 9.5 :(

**Comment by lead0r** [comment]
I don't know much about any of this, but I did a little digging based on the error message and I found that HA OS 10.0 had the following commit:

Bump dbus-broker to 33 (https://github.com/home-assistant/operating-system/pull/2340) @agners
[https://github.com/bus1/dbus-broker/releases/tag/v33](https://github.com/bus1/dbus-broker/releases/tag/v33)

Here is the corresponding changelog for dbus-broker 33: 
[https://github.com/bus1/dbus-broker/releases/tag/v33](https://github.com/bus1/dbus-broker/releases/tag/v33)

**Comment by agners** [comment]
Could be a ulimit issue, see this blog post: https://developers.home-assistant.io/blog/2023/04/13/new_limits_for_add_ons

Definitely worth trying to set the previous ulimit in you raddon start script.

**Comment by MaxWinterstein** [comment]
Sadly I can't reproduce this here, as I am not running HA OS. 

I updated my Docker installation to v23, but this does not get me further.

My best guess is similar to @agners - the ulimit stuff that also had me with the `adsb-multi-portal-feeder`. See e.g. #151 if interested.

I just added `ulimit -n` to all run tasks, as I have no real idea who and if someone is guilty of this.

In a few minutes the update to `2.2.0` should be available, feel free to test and give feedback ✌️

**Comment by lead0r** [comment]
Unfortunately, it still doesn't work. With a fresh install of 2.2.0 the log looks like this (and web interface is not accessible):

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/dbus-setup
cont-init: info: /etc/cont-init.d/dbus-setup exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun avahi (no readiness notification)
services-up: info: copying legacy longrun dbus (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[avahi] Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
[avahi] Successfully dropped root privileges.
[avahi] avahi-daemon 0.8 starting up.
[avahi] Successfully called chroot().
[avahi] Successfully dropped remaining capabilities.
[avahi] No service file found in /etc/avahi/services.
[avahi] Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.12.
[avahi] New relevant interface eth0.IPv4 for mDNS.
[avahi] Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
[avahi] New relevant interface lo.IPv4 for mDNS.
[avahi] Network interface enumeration completed.
[avahi] Server startup complete. Host name is homeassistant.local. Local service cookie is 3160859734.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
`

**Comment by orrpan** [comment]
Reopen issue or start a new?
