### ISSUE TITLE
OpenSky addon

### ISSUE THREAD

**Issue by yousaf465** [MaxWinterstein/homeassistant-addons#157]
can it be included in  ADS-B Multi Portal Feeder?
https://opensky-network.org/contribute/improve-coverage 

since a HA integration exist for it.
https://www.home-assistant.io/integrations/opensky/

**Comment by MaxWinterstein** [comment]
I saw you also opened this at the right place: https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues/121

**Comment by yousaf465** [comment]
Thomax has added it to the support, and now this add-on might be updated.
