### ISSUE TITLE
Trilium Notes 

### ISSUE THREAD

**Issue by yousaf465** [MaxWinterstein/homeassistant-addons#158]
https://community.home-assistant.io/t/is-there-a-trilium-notes-add-on-available/466807 

https://github.com/zadam/trilium

https://hub.docker.com/r/zadam/trilium

Trilium Notes add-on would be awesome.

**Comment by MaxWinterstein** [comment]
I don't think I can provide more time on new addons, specially on ones that I don't use myself.

May ask my friend https://github.com/alexbelgium/hassio-addons/issues - he might be able to cover this.

Sorry.
