### ISSUE TITLE
When new version released, old images are still on the system

### ISSUE THREAD

**Issue by skank01** [MaxWinterstein/homeassistant-addons#16]
I can see with portainer, that everytime a new version is released, the old image remains on the system
Is it possible to always delete the old version or overwrite it?

**Comment by MaxWinterstein** [comment]
Can confirm this behavior. 

Will have a look at how to improve this, not high prio.

**Comment by matijse** [comment]
This is how Docker works, due to every image having a new "tag". All images keep their tags, and they are not automatically removed. Docker re-uses unchanged "layers" between images, so the disk space it uses will not increase that much between images, if the base layers stay the same.

You can remove any images that are currently not in use with the command `docker image prune -a`. This will remove ANY image that isn't being used by a container at the moment.

**Comment by MaxWinterstein** [comment]
Well, technically you are correct @matijse, but there is some kind of cleanup process available. If we look at the logs of the supervisor (the thing that manages the addons and its installation, updates, deletion...) we can see after running some addon update:

```log
21-02-04 08:37:48 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image homeassistant/aarch64-addon-deconz:6.6.3 to homeassistant/aarch64-addon-deconz:6.6.4
21-02-04 08:37:48 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-deconz with tag 6.6.4.
21-02-04 08:37:52 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_core_deconz application
21-02-04 08:37:58 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_core_deconz application
21-02-04 08:37:58 INFO (SyncWorker_0) [supervisor.docker.interface] Cleanup images: ['homeassistant/aarch64-addon-deconz:6.6.3']
21-02-04 08:37:58 INFO (MainThread) [supervisor.addons] Add-on 'core_deconz' successfully updated
21-02-04 08:38:00 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-deconz with version 6.6.4
```

But, I did not investigate enough how that cleanup mechanism works. I might need to change the image building process a little, which had brought me some struggle.

**Comment by MaxWinterstein** [comment]
The add-on now uses prebuild container images that cleanup pretty well. Last one-time cleanup through e.g. `portainer` is a good idea ;)

/close
