### ISSUE TITLE
ADS-B Feeder : Add-on HTML_DEFAULT_TRACKER Configuration not in sync with lastest Thom-x 1.24.0

### ISSUE THREAD

**Issue by plo53** [MaxWinterstein/homeassistant-addons#163]
Hi Max,

There is a little missing.

- Thom-x 1.24.0 : HTML_DEFAULT_TRACKER | Default: FlightAware | Which flight tracker website to use by default. Possible values are FlightAware or Flightradar24 or Adsbexchange or Planefinder or OpenskyNetowrk

- adsb-multi-portal-feeder 1.24.0 : config.yaml : HTML_DEFAULT_TRACKER: list(FlightAware|Flightradar24)?

Thx

**Comment by MaxWinterstein** [comment]
Good catch, missed this one!

There is a typo in _OpenskyNet_**ow**_rk_ in the upstream.

For the moment I copied it, but created https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/128 to get it fixed.

Version `1.24.0.1` should be available in a few minutes.

**Comment by MaxWinterstein** [comment]
Done with #164 and with fixed upstream typo in #165
