### ISSUE TITLE
Feature: Add RadarBox for feeding

### ISSUE THREAD

**Issue by Shariner** [MaxWinterstein/homeassistant-addons#169]
Hi,

I am also feeding to radarBox on my dedicated RPI3 (in addition to Planefinder, FlightAware, FR24 and ADSBexchange). Maybe we can add support of radarBox in the future.

I would do it by myself if I had any experience in containers next of using them. So maybe someone can, on my dedicated RPI3, I just ran the Piaware image and ran the installation command and edited the configuration. 

Best regards 

RBFeeder install command:
sudo bash -c "$(wget -O - http://apt.rb24.com/inst_rbfeeder.sh)"

Path to config file (on usual systems) /etc/rbfeeder.ini (needs to be adjusted)

Sharing key configuration: sudo rbfeeder --setkey ‹your sharing key›

all setup guide:

https://www.radarbox.com/sharing-data/guide

**Comment by yousaf465** [comment]
wrong place 
, right path 

https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues

**Comment by Shariner** [comment]
@yousaf465 oh sorry, i was only on my phone. Dammit.

shall we close this as you opened up the ticket in the right place?

**Comment by yousaf465** [comment]
> @yousaf465 oh sorry, i was only on my phone. Dammit.
> 
> shall we close this as you opened up the ticket in the right place?

I have already opened it for you. Please continue the discussion there. 

 https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues/131

**Comment by yousaf465** [comment]
@Shariner it' done
