### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by Quarco** [MaxWinterstein/homeassistant-addons#176]
Fresh install of this VERY PROMISING addon in my HA resulted in error:

URL added repository:
https://github.com/MaxWinterstein/homeassistant-addons/

Result:
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/41013449/d9b38665-1ea7-4a12-9ab2-7ba649ae0c84)

**Comment by MaxWinterstein** [comment]
Works fine for me, just tried it on a fresh installation.

The wording 'cups' looks suspicious to me.

**Comment by Quarco** [comment]
That .... is ... strange...
Restarted my HA and it was accepted
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/41013449/758649d1-8f63-412a-8610-5d5d888d1867)

**Comment by Quarco** [comment]
No, not working!
It stops every time, I don't get the cups screen on port 631
Disabled SSL, so it should work

![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/41013449/ed625a02-1462-4aa1-b55c-c61d70f32a43)

**Comment by MaxWinterstein** [comment]
This is similar to #167  - let us continue this issue there :)
