### ISSUE TITLE
Please move eufy-ha-mqtt-bridge config files to correct place

### ISSUE THREAD

**Issue by timdonovanuk** [MaxWinterstein/homeassistant-addons#18]
Hi,

The right place for HA add-ons to store config data is.../data (I believe). The eufy-ha-mqtt-bridge plugin is currently storing it in /share/eufy-ha-mqtt-bridge.

Why does this matter? Some of the HA snapshot and backup plugins ignore /share because it's not supposed to have configuration items in it. If a user backups their HA and restores, this eufy-ha-mqtt-bridge plugin will be broken.

FWIW, I have 25 HA add-ons installed and the only plugin storing config files and log files in /share is eufy-ha-mqtt-bridge!

Cheers :)

**Comment by MaxWinterstein** [comment]
Reasonable to me. 

I did this on purpose as i tried to make it easy for everyone to access the log files in case they need support.

@matijse would it be possible to move log files to their own folder? E.g. just a subfolder?

**Comment by timdonovanuk** [comment]
Thanks :) Actually most other add-ons don't actually even expose the logs either, they're visible via the "Log" tab and that's all - I see you've already done that here and it works perfectly so I'm not sure it needs a folder. Although IIRC there are some additional debugging type logs produced with this integration. 

Anyway, thanks either way. I see your name popping up constantly in the eufy HA thread so thanks for all your hard work!!

**Comment by matijse** [comment]
@MaxWinterstein yes changing the log location is easy. What would be the use case? Would you not want it to be present in the data directory for backup purposes? (Logs don't need backing up?) Then it should be a different folder from the root right?

What would be best?

```
/logs/{log files}
/config/config.yml
```

or 

```
/data/logs/{log files}
/data/config.yml
```

**Comment by MaxWinterstein** [comment]
Mhm, well, not easy to decide. 
Mostly I am at @timdonovanuk and his point, it should be consistent with 'the other' add-ons. E.g. Backups are a good reason for that. 

Logging to stdout seems also to be the default. 

Having `/data` available at `/share` was mostly done to help you and the development of it. It allows users to easily access the database to extract missing camera information. But I think anyone who is advanced and able to extract the info out of the SQLite file is also able to do some other steps... Also the sqlite file is living inside the data folder as well...

I would propose the following:   
* We move the logs to a subfolder `logs`. This feels convenient to me.
* I add some config option to have the data-folder available at `/share` if someone wants to. 

I think this should allow the add-on to be like the others while still maintaining the possibility to extract the data for some advanced user.

**Comment by MaxWinterstein** [comment]
Removed the symlink from `/share` to `/appl/data`. Now `/data` will be symlinked to `/app/data`. 

I also added some `eval` configuration option that allows us to do some magic, like exporting the push payload for addin new devices. 

hope this serves all purposes well now :)

**Comment by matijse** [comment]
@MaxWinterstein Sorry for the delay, haven't had much time to do anything on the Eufy integration lately. 

Does your latest change mean that no change in the directory structure is needed anymore? If it is still preferred to change some things, let me know what the structure should be.

**Comment by MaxWinterstein** [comment]
Nothing to say sorry for, we all do this in our spare free time :)

Well, from add-on side it is 'just like the others' now. Afaik there is no common way to get logs from the others. Mostly you click the 'logs' tab and hope your issue is contained within the last ~100 lines of log that is visible. 

I added some hint to my documentation on how to copy the file logs to `/share` so it can be easily accessed. 

So, from my point, no todo for now.
