### ISSUE TITLE
OctoPrint Proxy - Incorrect username or password.

### ISSUE THREAD

**Issue by ouf746** [MaxWinterstein/homeassistant-addons#180]
hello I connected to octoprint through homeassistant, however when I connect with my username and my password I have an error message ->Incorrect username or password.
<img width="967" alt="Capture d’écran 2023-08-10 à 19 18 25" src="https://github.com/MaxWinterstein/homeassistant-addons/assets/121038958/7d9b317c-0644-4db4-917a-ab7f978ad799">
<img width="1154" alt="Capture d’écran 2023-08-10 à 19 19 15" src="https://github.com/MaxWinterstein/homeassistant-addons/assets/121038958/a36d1d05-4d2f-4ca0-9f35-925405dbe823">
<img width="1154" alt="Capture d’écran 2023-08-10 à 19 19 37" src="https://github.com/MaxWinterstein/homeassistant-addons/assets/121038958/11e7a56b-d466-4ac6-8026-12cc288a0c3b">

**Comment by mrwiwi** [comment]
Same here, working perfectly on direct access

**Comment by fraintt** [comment]
Same here, I think it is related to changes after OctoPrint 1.8.3 / 1.8.4, there are several users complaining about issues with their own reverse-proxy access to OctoPrint.

**Comment by MaxWinterstein** [comment]
Same problem as https://github.com/MaxWinterstein/homeassistant-addons/issues/115 - lets continue there, as it is the oldest issue for that
