### ISSUE TITLE
Multiple Instances of Octoprint?

### ISSUE THREAD

**Issue by Yith1** [MaxWinterstein/homeassistant-addons#2]
I've just been setting up Home Assistant tonight and found this addon.

It works great, but there's just one problem.

I have two instances of Octoprint that I'd like to have on Home Assistant and I can't see any way of setting them both up with this addon.

**Comment by MaxWinterstein** [comment]
well, pretty uncommon wish. 

What you could do, is simply download the `octoprint-proxy` folder and manually add it to your `addon` folder. E.g. via the `samba share` addon. Now you can adjust the `config.json` within the `octoprint-proxy` folder and add some `_2` or whatever you wish to the `slug` and `name`. 

This way you should have two addons installed, and one button for each addon possible.

**Comment by Yith1** [comment]
I'll give that a go. I did wonder if something like that was possible, but had no idea where to start.

**Comment by MaxWinterstein** [comment]
Sure thing. Hit me up if you encounter any problems ✌️
