### ISSUE TITLE
JS-controller update available from 3.1.6 to 3.2.16

### ISSUE THREAD

**Issue by tintim** [MaxWinterstein/homeassistant-addons#21]
First thank you Max for ioBroker via the HA addon repository, it works well for me with Eufy Camera's. This is a query on updating the ioBroker host.

**ioBroker host update available to 3.2.16**

**Message in GUI**
After intensive testing the new js-controller 3.2.16 is available now in the stable repository. No issues are known at the moment. More information on the changes and instructions can be found in forum at https://forum.iobroker.net/topic/42385/js-controller-3-2-jetzt-im-stable

_Unfortunately I'm unable to update using the upgrade process, after using SSH to HA I cannot locate ioBroker. Below are the instructions to update from the host._

**js-controller upgrade instructions**
Due to the different hardware and platforms under which ioBroker runs, the js-controller has to be updated manually. Further details can be found in the appropriate section.

**Linux/macOS (new installer)**
This is the recommended option !!

Please execute the following commands in an SSH shell (console):

iobroker stop
iobroker update
iobroker upgrade self
iobroker start or reboot server, then ioBroker should restart and you can be sure that all old processes were finished.
If the upgrade command displays Access Rights / Permission errors, then please use the install fixer (curl -sL https://iobroker.net/fix.sh | bash-) to fix these issues and upgrade command run again.

**Linux/macOS (manually installed)**
A manual installation usually takes place under root as user and therefore a "sudo" is necessary before the commands.

Please execute the following commands in an SSH shell (console):

cd /opt/iobroker
sudo iobroker stop
sudo iobroker update
sudo iobroker upgrade self
sudo iobroker start or server reboot, then ioBroker should restart and you can be sure that all old processes were finished.
If the upgrade command displays permissions / permissions errors, fix them. Sometimes "sudo" is not enough and you have to run the installation as a real root (previously simply sudo su -).

**Comment by MaxWinterstein** [comment]
Thanks for the info, will have a look on how i can get that upgraded.

(Simply jumping into the container might fail, i guess.)

**Comment by MaxWinterstein** [comment]
Coffee break solution here:  
There is some maintenance script available that lets us pause the iobroker iteself and use the update command.

Simply use portainer to jump into the container. I created some quick recording, might have a try?



[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=H7ovNJGdKR8)](https://www.youtube.com/watch?v=H7ovNJGdKR8 "Everything Is AWESOME")
[Youtube](https://www.youtube.com/watch?v=H7ovNJGdKR8&feature=youtu.be)

**Comment by tintim** [comment]
Thanks Max for the quick response. I've installed portainer but after accessing the primary instance I have zero containers. Just have 18 images and 4 networks. Can't help but think I've missed a step somewhere or it has something to do with my setup?

**Comment by MaxWinterstein** [comment]
As always, and I also hate to hear this, RTFM ;)

https://github.com/hassio-addons/addon-portainer/blob/main/portainer/DOCS.md#known-issues-and-limitations

**Comment by tintim** [comment]
Very good point :-P

All sorted thanks, had some errors on the upgrade self command but was fixed with "curl -sL https://iobroker.net/fix.sh | bash" iobroker restarted and installed 3.2.16.

Will drop you a coffee soon :-)

**Comment by MaxWinterstein** [comment]
> All sorted thanks, had some errors on the upgrade self command but was fixed with "curl -sL https://iobroker.net/fix.sh | bash" iobroker restarted and installed 3.2.16.

Nice hint!

Will try to dropt that to the readme for everyone intrested.

> Will drop you a coffee soon :-)

Awesome, thanks <3

**Comment by MaxWinterstein** [comment]
Updated iobroker addon to `0.8.0`. 

I added some documentation on howto upgrade the `js-controller` either via `portainer` or the new introduced `eval` option.

Fresh installations should have the new `js-controller` as it was updated in the base image.

Thanks again for the ☕️ :v:
