### ISSUE TITLE
CUPS 3.0.0 not compatible with HA running on Raspi architecture 

### ISSUE THREAD

**Issue by kds69** [MaxWinterstein/homeassistant-addons#219]
Hi, thanks for this add-on.
Seems this last version is not compatible or has not been compiled for Raspi architecure ?

**Comment by MaxWinterstein** [comment]
I quickly added support for `armhf` - which always confuses me what hardware this really covers.

As far as I know did the godfather _frenk_ start to remove `armhf` support from his stuff, saw this somewhere.

What hardware are you using, and is the addon supported now?

**Comment by kds69** [comment]
Raspberry 4B 4G
Thanks. In the meantime, I wondered if this wasn’t due to HAOS 32bit the issue.
Now moved to 64bit (for voice support).
3.0.0.1 installed successfully though an error message popped up at the end saying to check logs.
No error about CUPS install found and CUPS logs do show error.
This install not tested yet though.

**Comment by MaxWinterstein** [comment]
pretty sure it was related to 32bit, which is not really supported anymore. I mean - it's nearly 2024 ;)

let me know if you encounter anything strange.
