### ISSUE TITLE
502 Bad Gateway NOT WORKING message

### ISSUE THREAD

**Issue by silviudc** [MaxWinterstein/homeassistant-addons#231]
The octoprint proxy logs are filled with this error:
```
starting nginx
nginx: [emerg] invalid URL prefix in /etc/nginx/http.d/proxy.conf:7
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Any ideas what happened and also seeing this not working message
![image](https://github.com/MaxWinterstein/homeassistant-addons/assets/17740184/d4029676-d05e-449f-a667-6cd4acd719ef)

**Comment by MaxWinterstein** [comment]
yeah, it is currently not working ;)

See #115 for more information on that please.
