### ISSUE TITLE
ADSB Multi-Portal Feeder UI access not working

### ISSUE THREAD

**Issue by ggonmar** [MaxWinterstein/homeassistant-addons#234]
Hey there,
I installed the add-on and it is feeding information correctly within the add-on, but
When attempting to access http://homeassistant.local:8754 I cannot reach any result as shown on the setup guide, it shows the "could not reach" error.

Trying to follow the guide thoroughly, it states:
```
fr24feed (the feeder of FlightRader24) provides some stats at its internal port 8754.
To access add some external port at the configuration tab at Network like this:
```  

However, there is no configuration tab at Network on current instances of Home Assistant. 
Could you please review the guide to set this up?

Thank you!

**Comment by MaxWinterstein** [comment]
@ggonmar Not sure if I understand that correctly, but I think you are at the wrong spot. You need to go to the `Configuration` tab of the Add-On, not the Home Assistant Instance itself.

In general, it is working for me like this:

![Screenshot 2024-01-15 at 22 34 38](https://github.com/MaxWinterstein/homeassistant-addons/assets/5927148/0eb5b5e7-f89e-42c2-b2db-e720bfb7ddaf)

**Comment by ggonmar** [comment]
WOOOOOPS my bad!!! I totally misunderstood the manual myself - now I see where I had to input the port number.

Thank you!
