### ISSUE TITLE
Not able to pull the Dump1090 feed from my external system anymore

### ISSUE THREAD

**Issue by medivb** [MaxWinterstein/homeassistant-addons#249]
I love the ADS-B Multi-Portal Feeder Add-on! 

However, now I seem to be running into an issue:

Until I updated to Hass Core 2024.5.1 (learned to skip the .0), I was able to take my dump1090 feed from my external PI that is located with the antenna and distribute further to the various platforms using the add-on. This just stopped working. Is anyone else experiencing this as well? Any suggestions on how to get this working again? Updating Core to 2024.5.2 did not solve it.

**Comment by medivb** [comment]
These are some logs that are hopefully relevant:

 System: Home Assistant OS 12.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.5.2
s6-rc: info: service conf-adsbexchange successfully started
s6-rc: info: service adsbexchange-feed: starting
s6-rc: info: service adsbexchange-feed successfully started
s6-rc: info: service adsbexchange-stats: starting
s6-rc: info: service adsbexchange-mlat: starting
s6-rc: info: service adsbexchange-hassio-sensors: starting
s6-rc: info: service adsbexchange-mlat successfully started
s6-rc: info: service adsbexchange-hassio-sensors successfully started
s6-rc: info: service adsbexchange-stats successfully started
[fr24feed] 2024-05-07 16:11:48 | [feed][i]configuring decoder
[fr24feed] 2024-05-07 16:11:48 | [feed][c]Max range AIR: 350.0nm
[fr24feed] 2024-05-07 16:11:48 | [feed][c]Max range GND: 80.0nm
[fr24feed] 2024-05-07 16:11:48 | [feed][i]configuration changed
[fr24feed] 2024-05-07 16:11:48 | [feed][i]defined 3 servers
[fr24feed] 2024-05-07 16:11:48 | [feed][c]Timestamps: optional
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.318 [E][:] Local time: 2024-05-07 16:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [E][:] GMT+0 time: 2024-05-07 15:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [E][:] Your machine should be set as GMT+0 time zone!
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [W][:] Time zone is not set to GMT+0
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [I][receiver_ac_sender.cpp:137] Stopping ReceiverACSender threads for feed 
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [D][receiver_ac_sender.cpp:141] Stop called on non-running network thread for feed 
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.319 [I][receiver_ac_sender.cpp:96] Configured ReceiverACSender: 185.218.24.22:8099,185.218.24.23:8099,185.218.24.24:8099, feed: EHAM617, send_interval: 5s/1s, max age: 15s, send metadata: true, mode: 1, filtering: true
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] Local time: 2024-05-07 16:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] GMT+0 time: 2024-05-07 15:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] Your machine should be set as GMT+0 time zone!
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [W][:] Time zone is not set to GMT+0
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [I][crxstats.cpp:588] [stats]Stats thread started
[fr24feed] 2024-05-07 16:11:48 | [feed][n]EHAM617@185.218.24.22:8099/UDP
[fr24feed] 2024-05-07 16:11:48 | [feed][n]connecting
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] Local time: 2024-05-07 16:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] GMT+0 time: 2024-05-07 15:11:48 +0200
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [E][:] Your machine should be set as GMT+0 time zone!
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [W][:] Time zone is not set to GMT+0
[fr24feed] 2024-05-07 16:11:48 | 24-05-07 16:11:48.320 [I][receiver_ac_sender.cpp:36] Network thread connecting to 185.218.24.22:8099 for feed EHAM617
[fr24feed] 2024-05-07 16:11:48 | [feed][n]connected via UDP (fd 23)
[fr24feed] 2024-05-07 16:11:48 | [feed][n]working
 Home Assistant Supervisor: 2024.04.4

And this is my config:

SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: true
SERVICE_ENABLE_FR24FEED: true
SERVICE_ENABLE_HTTP: true
PIAWARE_FEEDER_DASH_ID: {redacted}
FR24FEED_FR24KEY: {redacted}
ADSBEXCHANGE_UUID: {redacted}
PLANEFINDER_SHARECODE: "123"
HTML_SITE_LAT: "{redacted}"
HTML_SITE_LON: "{redacted}"
HTML_SITE_ALT: "7"
SYSTEM_HTTP_ULIMIT_N: 1048576
SYSTEM_FR24FEED_ULIMIT_N: 1024
SERVICE_ENABLE_IMPORT_OVER_NETCAT: false
DUMP1090_REMOTE_HOST: {redacted}
DUMP1090_REMOTE_PORT: 30005
DUMP1090_ADDITIONAL_ARGS: >-
  --net-only --mlat --forward-mlat --net-bi-port 30004,30104 --net-bo-port 30005
  --json-location-accuracy 2 --net-heartbeat 30 --fix --fix
DUMP1090_LOCAL_PORT: 30004
SERVICE_ENABLE_PLANEFINDER: false
SERVICE_ENABLE_ADSBEXCHANGE: true
ADSBEXCHANGE_MLAT: false
ADSBEXCHANGE_STATION_NAME: {redacted}
MLAT_EXACT_LAT: "{redacted}"
MLAT_EXACT_LON: "{redacted}"
MLAT_ALTITUDE_MSL_METERS: "7"

**Comment by MaxWinterstein** [comment]
> I'm stupid... I see now that the SERVICE_ENABLE_IMPORT_OVER_NETCAT was false... Set to true and all is working fine. Was this added recently? I'm sure I didn't change this or remember seeing this before...

Yeah, kinda recently ;)

<img width="774" alt="image" src="https://github.com/MaxWinterstein/homeassistant-addons/assets/5927148/e341343e-1778-49a2-8dec-bc4d4cd86729">
