### ISSUE TITLE
ioBroker and HTTPS connections

### ISSUE THREAD

**Issue by hjorslev** [MaxWinterstein/homeassistant-addons#25]
I have my HA running on a Raspberry PI and configured it with HTTPS using Let's Encrypt and port forwarded it so I can access it e.g. on my phone.

However, I am not able to access ioBroker through port 8081. I have tried to port forward as well as trying to access through its local IP -- both with HTTP and HTTPS.

Does it only work with HTTP or could it also work with HTTPS?

**Comment by MaxWinterstein** [comment]
Using local IP and http should work totally fine.

![image](https://user-images.githubusercontent.com/5927148/114413202-0f67ae80-9bae-11eb-8da5-0e101fc03477.png)

Just to make sure, you are accessing it via the ip of your raspberry - just my screenshiot?

e.g.:
`http://192.168.1.2:8081`

**Comment by hjorslev** [comment]
It just occurred to me that this were a firewall issue on my end.... 🙈
