### ISSUE TITLE
Flightradar24 / Add-on does not stay active

### ISSUE THREAD

**Issue by renekar** [MaxWinterstein/homeassistant-addons#251]
Installed FR24 and run the add-on. It needs always 2-3 times until the map is showing up. If I change view in the frontend and come back to FR24 frontend, it tells em again the add-on is not working and to be started....
<img width="769" alt="Bildschirmfoto 2024-05-31 um 08 24 54" src="https://github.com/MaxWinterstein/homeassistant-addons/assets/14357153/722d7ae9-af5a-450f-8d2f-d853a1531c4a">

**Comment by MaxWinterstein** [comment]
Hi Rene,

might share some log output? It seems like it is restarting.

**Comment by renekar** [comment]
[fr24feed] 2024-05-31 11:33:35 | [main][i]Copyright 2012-2023 Flightradar24 AB
[fr24feed] 2024-05-31 11:33:35 | [main][i]https://www.flightradar24.com
[fr24feed] 2024-05-31 11:33:35 | [main][i]DNS mode: PING
[fr24feed] 2024-05-31 11:33:35 | error | Local time: 2024-05-31 11:33:35 +0200
[fr24feed] 2024-05-31 11:33:35 | error | GMT+0 time: 2024-05-31 10:33:35 +0200
[fr24feed] 2024-05-31 11:33:35 | error | Your machine should be set as GMT+0 time zone!
[fr24feed] 2024-05-31 11:33:35 | warning | Time zone is not set to GMT+0
[fr24feed] 2024-05-31 11:33:35 | [main][i]Automatic updates are DISABLED
[fr24feed] 2024-05-31 11:33:35 | 24-05-31 11:33:35.788 [E][:] Local time: 2024-05-31 11:33:35 +0200
[fr24feed] 2024-05-31 11:33:35 | 24-05-31 11:33:35.788 [E][:] GMT+0 time: 2024-05-31 10:33:35 +0200
[fr24feed] 2024-05-31 11:33:35 | 24-05-31 11:33:35.788 [E][:] Your machine should be set as GMT+0 time zone!
[fr24feed] 2024-05-31 11:33:35 | 24-05-31 11:33:35.788 [W][:] Time zone is not set to GMT+0
[fr24feed] 2024-05-31 11:33:35 | 24-05-31 11:33:35.788 [I][http-server.cpp:246] [httpd]Server started, listening on :::8754
[fr24feed] 2024-05-31 11:33:35 | [i]PacketSenderConfiguration::fetch_config(): Yoda configuration for this receiver is disabled
[fr24feed] 2024-05-31 11:33:35 | [d]TLSConnection::ctor(): Enable verify_peer in production code!
[fr24feed] 2024-05-31 11:33:35 | [main][i]Reader thread started
[fr24feed] 2024-05-31 11:33:35 | [master][i]Starting processing thread
[fr24feed] 2024-05-31 11:33:35 | [reader][i]Initializing reader
[fr24feed] 2024-05-31 11:33:35 | [reader][i]Connecting to unknown receiver via (tcp://127.0.0.1:30005)
[fr24feed] 2024-05-31 11:33:35 | [reader][i]Connected to the receiver, configuring
[fr24feed] 2024-05-31 11:33:35 | [reader][i]Configured, processing messages
[fr24feed] 2024-05-31 11:33:35 | [time][i]Synchronizing time via NTP
 System: Home Assistant OS 12.3  (aarch64 / raspberrypi5-64)
[flightradar-hassio] Starting Flightradar24 hassio sensors api
 Home Assistant Core: 2024.5.5
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service banner: stopping
s6-rc: info: service radarbox: stopping
s6-rc: info: service planefinder-log: stopping
s6-rc: info: service planefinder-hassio-sensors: stopping
s6-rc: info: service opensky-hassio-sensors: stopping
s6-rc: info: service netcat: stopping
s6-rc: info: service http: stopping
s6-rc: info: service fr24feed-hassio-sensors: stopping
s6-rc: info: service adsbhub: stopping
s6-rc: info: service adsbfi-mlat: stopping
s6-rc: info: service adsbfi-hassio-sensors: stopping
s6-rc: info: service adsbexchange-stats: stopping
s6-rc: info: service adsbexchange-mlat: stopping
s6-rc: info: service adsbexchange-hassio-sensors: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service opensky-hassio-sensors successfully stopped
s6-rc: info: service opensky: stopping
s6-rc: info: service radarbox successfully stopped
s6-rc: info: service conf-radarbox: stopping
s6-rc: info: service planefinder-log successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service planefinder-hassio-sensors successfully stopped
s6-rc: info: service planefinder: stopping
s6-rc: info: service netcat successfully stopped
s6-rc: info: service http successfully stopped
s6-rc: info: service init-upintheair: stopping
s6-rc: info: service confd-layers: stopping
s6-rc: info: service confd-html: stopping
s6-rc: info: service fr24feed-hassio-sensors successfully stopped
s6-rc: info: service fr24feed: stopping
s6-rc: info: service adsbhub successfully stopped
s6-rc: info: service conf-adsbhub: stopping
s6-rc: info: service adsbfi-mlat successfully stopped
s6-rc: info: service adsbfi-hassio-sensors successfully stopped
s6-rc: info: service adsbfi-feed: stopping
s6-rc: info: service adsbexchange-stats successfully stopped
s6-rc: info: service adsbexchange-mlat successfully stopped
s6-rc: info: service adsbexchange-hassio-sensors successfully stopped
s6-rc: info: service adsbexchange-feed: stopping
s6-rc: info: service opensky successfully stopped
s6-rc: info: service conf-opensky: stopping
s6-rc: info: service conf-radarbox successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service planefinder successfully stopped
s6-rc: info: service conf-planefinder: stopping
s6-rc: info: service init-upintheair successfully stopped
s6-rc: info: service confd-layers successfully stopped
s6-rc: info: service confd-html successfully stopped
s6-rc: info: service fr24feed successfully stopped
s6-rc: info: service confd-fr24feed: stopping
s6-rc: info: service conf-adsbhub successfully stopped
s6-rc: info: service adsbfi-feed successfully stopped
s6-rc: info: service conf-adsbfi: stopping
s6-rc: info: service adsbexchange-feed successfully stopped
s6-rc: info: service conf-adsbexchange: stopping
s6-rc: info: service dump1090: stopping
s6-rc: info: service conf-opensky successfully stopped
s6-rc: info: service conf-planefinder successfully stopped
[fr24feed] 2024-05-31 11:33:36 | [time][i]Time synchronized correctly, offset -0.007 seconds
[fr24feed] 2024-05-31 11:33:36 | [main][i]Feed Network client started
[fr24feed] 2024-05-31 11:33:36 | [feed][i]Downloading configuration
[fr24feed] 2024-05-31 11:33:36 | [feed][d]Fetching configuration
s6-rc: info: service confd-fr24feed successfully stopped
s6-rc: info: service conf-adsbfi successfully stopped
s6-rc: info: service conf-adsbexchange successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service dump1090 successfully stopped
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by renekar** [comment]
...when restarting I get a different log/errors

s6-rc: info: service dump1090 successfully stopped
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service dump1090: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service dump1090 successfully started
s6-rc: info: service netcat: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-upintheair: starting
s6-rc: info: service confd-piaware: starting
s6-rc: info: service confd-layers: starting
s6-rc: info: service confd-html: starting
s6-rc: info: service confd-fr24feed: starting
s6-rc: info: service conf-radarbox: starting
s6-rc: info: service conf-planefinder: starting
s6-rc: info: service conf-opensky: starting
s6-rc: info: service conf-adsbhub: starting
s6-rc: info: service conf-adsbfi: starting
s6-rc: info: service conf-adsbexchange: starting
s6-rc: info: service banner: starting
s6-rc: info: service netcat successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started

-----------------------------------------------------------
2024-05-31T11:36:54+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[345]: INFO Backend set to env
2024-05-31T11:36:54+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[345]: INFO Starting confd
2024-05-31T11:36:54+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[345]: INFO Backend source(s) set to 
2024-05-31T11:36:54+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[345]: INFO Target config /usr/lib/fr24/public_html/layers.js out of sync
2024-05-31T11:36:54+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[345]: INFO Target config /usr/lib/fr24/public_html/layers.js has been updated
s6-rc: info: service confd-layers successfully started
s6-rc: info: service conf-planefinder successfully started
s6-rc: info: service planefinder: starting
s6-rc: info: service conf-adsbexchange successfully started
s6-rc: info: service adsbexchange-feed: starting
s6-rc: info: service planefinder successfully started
s6-rc: info: service planefinder-log: starting
s6-rc: info: service planefinder-hassio-sensors: starting
s6-rc: info: service adsbexchange-feed successfully started
s6-rc: info: service adsbexchange-stats: starting
s6-rc: info: service adsbexchange-mlat: starting
s6-rc: info: service adsbexchange-hassio-sensors: starting
s6-rc: info: service conf-adsbhub successfully started
s6-rc: info: service adsbhub: starting
s6-rc: info: service init-upintheair successfully started
s6-rc: info: service planefinder-log successfully started
s6-rc: info: service planefinder-hassio-sensors successfully started
s6-rc: info: service adsbexchange-hassio-sensors successfully started
s6-rc: info: service adsbhub successfully started
s6-rc: info: service adsbexchange-stats successfully started
s6-rc: info: service adsbexchange-mlat successfully started
[dump1090] Fri May 31 11:36:55 2024 CEST  dump1090-fa v9.0 starting up.
s6-rc: info: service conf-adsbfi successfully started
s6-rc: info: service adsbfi-feed: starting
 Add-on: ADS-B Multi-Portal Feeder
s6-rc: info: service conf-radarbox successfully started
s6-rc: info: service radarbox: starting
s6-rc: info: service adsbfi-feed successfully started
s6-rc: info: service adsbfi-mlat: starting
s6-rc: info: service adsbfi-hassio-sensors: starting
s6-rc: info: service radarbox successfully started
s6-rc: info: service conf-opensky successfully started
s6-rc: info: service opensky: starting
[dump1090] rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
s6-rc: info: service adsbfi-hassio-sensors successfully started
s6-rc: info: service adsbfi-mlat successfully started
s6-rc: info: service opensky successfully started
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[759]: INFO Backend set to env
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[759]: INFO Starting confd
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[759]: INFO Backend source(s) set to 
s6-rc: info: service opensky-hassio-sensors: starting
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[759]: INFO Target config /etc/fr24feed.ini out of sync
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[759]: INFO Target config /etc/fr24feed.ini has been updated
s6-rc: info: service confd-fr24feed successfully started
s6-rc: info: service fr24feed: starting
s6-rc: info: service opensky-hassio-sensors successfully started
[dump1090] Detached kernel driver
s6-rc: info: service fr24feed successfully started
s6-rc: info: service fr24feed-hassio-sensors: starting
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[848]: INFO Backend set to env
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[848]: INFO Starting confd
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[848]: INFO Backend source(s) set to 
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[848]: INFO Target config /usr/lib/fr24/public_html/config.js out of sync
2024-05-31T11:36:55+02:00 f1c878cb-adsb-multi-portal-feeder /opt/confd/bin/confd[848]: INFO Target config /usr/lib/fr24/public_html/config.js has been updated
s6-rc: info: service fr24feed-hassio-sensors successfully started
[piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!
[piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!
s6-rc: info: service confd-html successfully started
[piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!
s6-rc: info: service http: starting
[piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!
[piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!
s6-rc: info: service http successfully started
s6-rc: warning: unable to start service confd-piaware: command exited 1
[dump1090] Found Rafael Micro R820T tuner
 Dump1090 based feeder for FlightRadar24, FlightAware and more
-----------------------------------------------------------
[dump1090] rtlsdr: tuner gain set to 49.6 dB (gain step 28)
[dump1090] Allocating 4 zero-copy buffers

**Comment by MaxWinterstein** [comment]
> [piaware] FATAL: PIAWARE_FEEDER_DASH_ID not set!

You should either provide a dash id for piaware, or disable the feeder.

**Comment by renekar** [comment]
I disabled, and now it's working. Thanks
