### ISSUE TITLE
Crash when starting eufy add-on for the first time(s).

### ISSUE THREAD

**Issue by rwifall** [MaxWinterstein/homeassistant-addons#31]
When I try to start the eufy add-on, I get a connection reset error.
This prevents me from using this add-on as I can't get it to start.
Have you seen this?  Any workarounds?

**This is the error:**
`{"error":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"level":"error","message":"uncaughtException: read ECONNRESET\nError: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)","exception":true,"date":"Sun Apr 25 2021 00:35:32 GMT-0700 (Pacific Daylight Time)","process":{"pid":356,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.16.1","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":48922624,"heapTotal":17084416,"heapUsed":10133204,"external":2250985,"arrayBuffers":661904}},"os":{"loadavg":[0.67,0.46,0.5],"uptime":559444},"trace":[{"column":20,"file":"internal/stream_base_commons.js","function":"TCP.onStreamRead","line":209,"method":"onStreamRead","native":false}],"timestamp":"2021-04-25T07:35:32.955Z"}`

**This is the log:**
```
[00:35:23] INFO: Generating config.yml from options.json
[00:35:23] INFO: Image build with version 0.2.17
[00:35:23] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-04-25T07:35:29.808Z"}
info: Stored device: Doorbell (XXXXXXXXXXXXXXXX - type: T8201) {"timestamp":"2021-04-25T07:35:32.341Z"}
(node:356) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-25T07_35_33_098Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by MaxWinterstein** [comment]
What MQTT broker are you using? I think i have seen this with missaligned timeout settings.

Can you try some smaller keepalive?

e.g.

```yaml
eufy:
  username: XXX
  password: XXX
mqtt:
  url: 'mqtt://XXX'
  username: XXX
  password: XXX
  keepalive: 10
home_assistant:
  off_delay: 5
log_level: debug
eval: ''

```

**Comment by rwifall** [comment]
I looked into this more, and the issue was just that it wasn't connecting to the mqtt server.
This was because the configuration string wasn't set properly to use TLS, but the server was using TLS.
