### ISSUE TITLE
Invalid Add-on repository!

### ISSUE THREAD

**Issue by dimitribellini** [MaxWinterstein/homeassistant-addons#33]
Versions:
core-2021.6.6
supervisor-2021.06.3
Home Assistant OS 5.13

Detail:
I have try to add the repo for eufy-ha-mqtt-bridge (https://github.com/MaxWinterstein/homeassistant-addons/) i receive the message "Invalid Add-on repository!".
Is my fault or there are problem with my specific version of HomeAssistant?
Thanks so much

**Comment by dimitribellini** [comment]
Sorry... I now have retry to add the repo (https://github.com/MaxWinterstein/homeassistant-addons) and IT WORK!
So i close the issue...
Thanks and sorry

**Comment by MaxWinterstein** [comment]
No worries, happy to see it working :)
