### ISSUE TITLE
Sensors immediately become unavailable

### ISSUE THREAD

**Issue by joshmd** [MaxWinterstein/homeassistant-addons#34]
Got the wireless battery powered doorbell to be recognised and added to the MQTT but after 1 second it all the sensors become unavailable.

My MQTT log also looks like this:

1624557936: Socket error on client <unknown>, disconnecting.
1624558056: New connection from 172.30.32.2 on port 1883.
1624558056: Socket error on client <unknown>, disconnecting.
1624558176: New connection from 172.30.32.2 on port 1883.
1624558176: Socket error on client <unknown>, disconnecting.
1624558296: New connection from 172.30.32.2 on port 1883.
1624558296: Socket error on client <unknown>, disconnecting.
1624558416: New connection from 172.30.32.2 on port 1883.
1624558416: Socket error on client <unknown>, disconnecting.
1624558536: New connection from 172.30.32.2 on port 1883.
1624558536: Socket error on client <unknown>, disconnecting.

**Comment by MaxWinterstein** [comment]
Hi @joshmd,

please post this at the MQTT bridge itselfs repo: https://github.com/matijse/eufy-ha-mqtt-bridge

this is just the 'wrapper' around it ;)

Greetings
Max
