### ISSUE TITLE
Camera refused?

### ISSUE THREAD

**Issue by RossEm0174** [MaxWinterstein/homeassistant-addons#35]
Hi, I installed the plugin to see that my doorbell camera got rejected right away!
but why? 

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/87038988/124654950-7f30c100-de9f-11eb-9e57-bce56e908b59.png">

**Comment by MaxWinterstein** [comment]
Hi @RossEm0174,

please post this at the MQTT bridge itselfs repo: https://github.com/matijse/eufy-ha-mqtt-bridge

this is just the 'wrapper' around it ;)

Greetings
Max
