### ISSUE TITLE
Error updating to 1.19.0

### ISSUE THREAD

**Issue by Snuffy2** [MaxWinterstein/homeassistant-addons#38]
Running on RPi 4 running Raspberry Pi OS Buster. Error when I click on Update from Supervisor:

`Can't install maxwinterstein/homeassistant-addon-eufy-ha-mqtt-bridge-armv7:1.19.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.19.0&fromImage=maxwinterstein%2Fhomeassistant-addon-eufy-ha-mqtt-bridge-armv7: Not Found ("manifest for maxwinterstein/homeassistant-addon-eufy-ha-mqtt-bridge-armv7:1.19.0 not found: manifest unknown: manifest unknown")`

**Comment by MaxWinterstein** [comment]
Indeed, 1.19 is broken for armv7. Will try to fix the Dockerfile.

Sadly there was no error at building the images, did not notice it...

**Comment by mmz06** [comment]
Hi There,
Running it in a Docker/Unraid environment, I got pretty much the same error, but related to i386:

`Can't install maxwinterstein/homeassistant-addon-eufy-ha-mqtt-bridge-i386:1.19.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.19.0&fromImage=maxwinterstein%2Fhomeassistant-addon-eufy-ha-mqtt-bridge-i386: Not Found ("manifest for maxwinterstein/homeassistant-addon-eufy-ha-mqtt-bridge-i386:1.19.0 not found: manifest unknown: manifest unknown")`

Should you provide help here also ?

**Comment by MaxWinterstein** [comment]
Hi,

I am currently fixing this thing. As building the image takes ~45min for some architectures it's time-consuming. 

It is a bad dependency problem. Some node component that is used is not available pre-compiled on all platforms and compiling is even more pain...

**Comment by mmz06** [comment]
Thank you !

**Comment by Helexx** [comment]
Hey max, does this also relate on adding your add-ons to HA?
I cant add the the add-ons at this moment:
21-07-08 11:14:01 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/MaxWinterstein/ repository
21-07-08 11:14:01 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/MaxWinterstein/ repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/MaxWinterstein/ /data/addons/git/99ad3ceb
  stderr: 'Cloning into '/data/addons/git/99ad3ceb'...
remote: Not Found
fatal: repository 'https://github.com/MaxWinterstein/' not found
'.

**Comment by MaxWinterstein** [comment]
> Hey max, does this also relate on adding your add-ons to HA?
> I cant add the the add-ons at this moment:
> 21-07-08 11:14:01 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/MaxWinterstein/ repository
> 21-07-08 11:14:01 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/MaxWinterstein/ repository: Cmd('git') failed due to: exit code(128)
> cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/MaxWinterstein/ /data/addons/git/99ad3ceb
> stderr: 'Cloning into '/data/addons/git/99ad3ceb'...
> remote: Not Found
> fatal: repository 'https://github.com/MaxWinterstein/' not found
> '.

Not sure, but did you use the correct url? https://github.com/MaxWinterstein/homeassistant-addons/ - looks like the last part `homeasisstant-addons` is missing?

---

@mmz06 @Snuffy2  can you have a try?

**Comment by mmz06** [comment]
> @mmz06 @Snuffy2 can you have a try with the new version `1.20.0`?

Perfectly working now from my side !
Thanks again 👍

**Comment by Helexx** [comment]
Not sure what went wrong, but i was able to add it again and update to 1.20.0

**Comment by Snuffy2** [comment]
Updated sucessfully to 1.20.0, thanks!
