### ISSUE TITLE
Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by ratleback** [MaxWinterstein/homeassistant-addons#39]
For few days I got this error and don't know why. I still can log in with this account on the eufy app.
![screenshot_1625645258](https://user-images.githubusercontent.com/62251024/124723374-31669800-df35-11eb-978b-fd00ef784468.png)

**Comment by matijse** [comment]
You should not use the same account in the add-on and in the app. Create a different account and use that account only in the add-on... (see https://github.com/matijse/eufy-ha-mqtt-bridge/#create-a-second-eufy-account)

**Comment by ratleback** [comment]
Yes, I used a different account and it can be logged in normally on app then I change to main account but now the sensors just become unavailable hourly.

**Comment by vlumikero** [comment]
I’ve had this issue on and off. Most recently, I just turned off the add on for a few hours to make sure it wasn’t a repeated login issue, worked for me.
