### ISSUE TITLE
Eufy - simplify Docker image

### ISSUE THREAD

**Issue by matijse** [MaxWinterstein/homeassistant-addons#41]
After all the issues with the image processing library, I decided to remove it altogether. I also removed the SQLite database, as it wasn't really needed.

This means images are building much faster now, and hopefully work on all architectures again... My image is now based on the node alpine image, with no extra dependencies. 

You might want to adjust your Dockerfile to remove the unneeded dependencies and speed up the build process...

**Comment by MaxWinterstein** [comment]
Hi @matijse 

good Job! I am happy to see this improvement towards compatibility. 

I removed the `sqlite` and `vips` stuff. Image builds are now way faster! 

You might want to adjust https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 according the new workflow?
