### ISSUE TITLE
MQTT bridge Eufy not startin

### ISSUE THREAD

**Issue by jtbmedia** [MaxWinterstein/homeassistant-addons#43]
Hi,

I get the following error in the logs:

`[17:01:24] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
(node:352) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable
    at EufyHttp.refreshStoredDevices (/app/eufy/http.js:45:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EufyClient.init (/app/eufy/client.js:17:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-03T15_01_27_283Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...

**Comment by MaxWinterstein** [comment]
Looks pretty known to me. Do you use a separete account for the addon?
