### ISSUE TITLE
Addon slug of tgtg-ha-mqtt-bridge not working with hassio.addon_stop

### ISSUE THREAD

**Issue by marcetad** [MaxWinterstein/homeassistant-addons#5]
Hi Max,

First of all, nice addon. Working good. 

Made an automation (with node-red) to receive a telegram message when stock is available. 
Now trying to shutdown the addon after the message is send. Next day at a specific time to start the addon. The problem is the current slug of the addon. In my case the slug is  "f1c878cb-tgtg-ha-mqtt-bridge". Looks like the problem are the dash symbols. Is it possible to replace the dash symbols by underscore's? (when i try to shutdown a different addon, 243ffc37_syncthing no problems occur)

Would it be possible to increase the polling time? Looks likes it polls every 30 seconds. I would like to run the addon just for +-10 minutes and increase the polling time. This because of some popular 'magix boxes' ;)

**Comment by MaxWinterstein** [comment]
btw, i moved this issue to the addon repository as it is not bridge-related itself

**Comment by MaxWinterstein** [comment]
Short update, this has been fixed on the `dev` branch via https://github.com/home-assistant/core/pull/46784 and should be in the next release 🥳

**Comment by MaxWinterstein** [comment]
Released with `2021.3.1`(?)

Please test :)

**Comment by marcetad** [comment]
Working fine now! Thanks Max
