### ISSUE TITLE
Portainer can't add new Endpoints

### ISSUE THREAD

**Issue by EpicLPer** [MaxWinterstein/homeassistant-addons#50]
When trying to add new Endpoints it shows this at the very top:
```Portainer has been started using the --external-endpoints flag. Endpoint management via the UI is disabled```

In general there seem to be quite a few issues with this cloned repo, when trying to go to any of the tabs to the left it simply shows `Object not found inside the database`.

**Comment by MaxWinterstein** [comment]
Can't really reproduce this behavior. Mind sharing your setup?

**Comment by fraintt** [comment]
Hi,
I have the same issue. With the "native" portainer addon I´m able, under the left menu "Endpoints" add new Endpoints (remote docker installations with portainer agent installed) to the portainer installation.

With your version I only get the error message as EpicLPer reported as well "Portainer has been started using the --external-endpoints flag. Endpoint management via the UI is disabled".

**Comment by MaxWinterstein** [comment]
I switched to https://github.com/alexbelgium/hassio-addons and his portainer add-on.

Please do so too, as my version is deprecated.
