### ISSUE TITLE
[ADS-B Multi-Portal Feeder] External feeds to addon

### ISSUE THREAD

**Issue by Calimerorulez** [MaxWinterstein/homeassistant-addons#54]
Hi,

Thanks you for creating this addon :)

Is it possible to let external instances feed data to this addon? I've got an instance of piAware running on a Raspberry Pi, and I would like to feed that data to this addon, so I can display it in HA.

If I start the addon, it complains no rtl-sdr is found, and that is obviously correct, but I noticed that in the config page, I can a specify incoming data port.

Thanks!

**Comment by yousaf465** [comment]
For that you don't need this add-on. for that use this https://community.home-assistant.io/t/flightradar24-as-an-add-on/75081/27

**Comment by Calimerorulez** [comment]
Thanks @yousaf465!
