### ISSUE TITLE
Missing possibility to ingest json with flight data from other device

### ISSUE THREAD

**Issue by medivb** [MaxWinterstein/homeassistant-addons#57]
Hi there, 

I really like the PiAware integration, but (I guess like many others), having the actual receiver located in the location my Home Assistant server is, is not really an option. I have a zero that now runs everything for Flightaware and FR24. Would it be an option to allow ingesting the raw data from there and have all processing actually run on the home assistant server in your add-on?

Cheers,

Medi

**Comment by yousaf465** [comment]
why would you need this addon? processing is already done by raspberry pi zero.

**Comment by MaxWinterstein** [comment]
@medivb i guess this should be possible. afair the core component ‘dump1090’ does have a `—net-only` option to fetch data from a remote instance. This could be the pi. 

I also moved away from using the adsb stick directly at the home assistant server to a pi zero w2 that is outside of the building. Was thinking about using it the way you told. So the zero just serves the raw data towards the HA server where it is splitted for all consumers.

Not sure if the add on provides these feature currently, and need to look at the base image is derrivated of.

Maybe not today, but will have an eye on this 👍

**Comment by medivb** [comment]
@MaxWinterstein thanks! Looking forward to this. Would be awesome to have it in such a setup, but unfortunately I lack the knowledge to make such changes myself...

**Comment by medivb** [comment]
> why would you need this addon? processing is already done by raspberry pi zero.

I want to place the zero in a box outside and just feed the raw data from it. Having is also as my web interface to view the processed results just does not make sense in my opinion...

**Comment by MaxWinterstein** [comment]
@medivb this is now possible 🥳 

I also have some external raspberry pi exposing data. I am running a full https://github.com/sdr-enthusiasts/docker-readsb-protobuf stack there, but it is painly slow. Image updates are eating up swap space...

I use the addon to fetch the data from the remote pi and feed it into the dump1090 of this addon. So i can e.g. feed planefinder.

Example config:
```yaml

SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: false
SERVICE_ENABLE_FR24FEED: false
SERVICE_ENABLE_HTTP: true
PIAWARE_FEEDER_DASH_ID: 123
FR24FEED_FR24KEY: 123
ADSBEXCHANGE_UUID: ''
PLANEFINDER_SHARECODE: 123
HTML_SITE_LAT: 50.0
HTML_SITE_LON: 8.0
SERVICE_ENABLE_IMPORT_OVER_NETCAT: true
DUMP1090_REMOTE_HOST: 192.168.1.125
DUMP1090_REMOTE_PORT: 30005
DUMP1090_ADDITIONAL_ARGS: >-
  --net-only --mlat --forward-mlat --net-bi-port 30004,30104 --net-bo-port 30005
  --json-location-accuracy 2 --net-heartbeat 30 --fix --fix
DUMP1090_LOCAL_PORT: 30004
SERVICE_ENABLE_PLANEFINDER: true
``` 


Inspired by https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/31#issuecomment-775729076

**Comment by medivb** [comment]
Works like a charm! Thanks!
