### ISSUE TITLE
Motion detected sensor for Floodlight Camera (T8420) not working

### ISSUE THREAD

**Issue by VectorC** [MaxWinterstein/homeassistant-addons#6]
Hi, I have a Floodlight Camera (T8420), my phone can receive a notification when motion is detected but not in Hass.
Firmware version1.0.0.32 and Hardware version 2.2 if that helps.

**Comment by MaxWinterstein** [comment]
Hi, as i only provide the Add-on pls open your issue at the bridge itself:

https://github.com/matijse/eufy-ha-mqtt-bridge

Greetings
