### ISSUE TITLE
Mode-S-Beast

### ISSUE THREAD

**Issue by CzarofAK** [MaxWinterstein/homeassistant-addons#62]
is the modesbeast also supported?

**Comment by CzarofAK** [comment]
the ModeSBeast is not supported. the RTLSDR USB stick works fine.
Is it possible to add the ModeSBeast as a supported device?

**Comment by MaxWinterstein** [comment]
> Is it possible to add the ModeSBeast as a supported device?

I guess it would be possible somehow, but without access to the hardware, it is pretty hard for me. 
This might be a good start for such an idea: https://discussions.flightaware.com/t/mode-s-beast-to-dump1090/18343

So, to be honest, I would be happy to help, but in that case I just can't. Sorry.
