### ISSUE TITLE
Eufy Home Assistant MQTT Bridge

### ISSUE THREAD

**Issue by Rogiertw** [MaxWinterstein/homeassistant-addons#63]
I installed this awesome add-on after installing my Eufy Battery doorbell combined with the Homebase 2. Installationmanual was clear and soon I received the data via MQTT. But today, 1 day later the entities where all unavailable and I saw an error in the MQTT log;
Any idea what the issue could be? I haven't changed anything from when it was working...

The erroe from the log of the add-on:

> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2022-02-07T10:39:31.893Z"}
info: Credentials found -> reusing them... {"timestamp":"2022-02-07T10:39:37.034Z"}
error: Error -- httpService.registerPushToken Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2022-02-07T10:39:37.411Z"}

**Comment by Rogiertw** [comment]
Ok, I found out that I hadn't configured my 2nd account. My bad, but online I also read that the 'Failed to request' error comes from too many logins at Eufy. Any ideas on how to avoid that?

**Comment by MaxWinterstein** [comment]
Not really, sorry. Maybe digging through the issues at the project upstream might help 👍
