### ISSUE TITLE
GPS Position sync with HOME

### ISSUE THREAD

**Issue by CzarofAK** [MaxWinterstein/homeassistant-addons#64]
It would be cool to link the HOME location of HA directly, instead of entering it manually.
This is specially intersting for people who install this in a motorhome or other mobile stations.

**Comment by MaxWinterstein** [comment]
As mentioned in the HA community, i guess a few lines of code around some init script could do the job.

Message ID: ***@***.***>

Will put this on my to-do, but on a very low position, as time is rare. :+1:

**Comment by MaxWinterstein** [comment]
note to my even more tired self:

```bash
curl -X GET -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" -H "Content-Type: application/json" http://supervisor/core/api/config | jq '.latitude'
curl -X GET -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" -H "Content-Type: application/json" http://supervisor/core/api/config | jq '.longitude'
curl -X GET -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" -H "Content-Type: application/json" http://supervisor/core/api/config | jq '.elevation'
```

**Comment by MaxWinterstein** [comment]
Found some time and added the _magic vars_:

- `HOMEASSISTANT_LATITUDE`
- `HOMEASSISTANT_LONGITUDE`
- `HOMEASSISTANT_ELEVATION`

pls have a try :)
