### ISSUE TITLE
Please update ADSB / Piaware / FR24

### ISSUE THREAD

**Issue by Delta1977** [MaxWinterstein/homeassistant-addons#65]
Hi, you are on version 1.7 Please update to 1.8.1 
https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/releases

**Comment by Delta1977** [comment]
i testet thomx/fr24feed-piaware:1.8.5 and bashio  v0.14.3. in a fork  and it works fine

**Comment by MaxWinterstein** [comment]
I updated to 1.8.5, pls have a test as my ADSB hardware is not accessible at the moment.

I also tried to align with 1.9.0 but the s6-init update to v3 gave me a hard time. Maybe with more sleep...

**Comment by Delta1977** [comment]
Thank you. It’s working on my side.

**Comment by MaxWinterstein** [comment]
Great! Will take care of >=1.9.0 when there is something useful.
