### ISSUE TITLE
please add adsbexchange.

### ISSUE THREAD

**Issue by theeddie** [MaxWinterstein/homeassistant-addons#67]
adsbexchange. is the most open exchange, no blocking and free

**Comment by Delta1977** [comment]
@MaxWinterstein  
Hi, Thom-x is working on adsbexchange-Support (https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/80) .
Maybe you find some time to get your Add-On on S6 support so you can adopt the new releases.
Thank you

**Comment by MaxWinterstein** [comment]
Ah, seems like this is needed way earlier than I hoped for 😁 

Will have a look at the S6 thing. 

Just need to find a better way how to handle development. Currently my RPi4 setup gives me a headache as e.g. docker logs are unusable. Tried the vscode way with development containers but in the tight-packed time I can spare for this project I did not find a nice workflow for me...

**Comment by MaxWinterstein** [comment]
Had some quick look, and again been stuck at this error line:
```bash
s6-overlay-suexec: fatal: can only run as pid 1
```

For the moment, after a quick search, no idea 😞

**Comment by Delta1977** [comment]
> Had some quick look, and again been stuck at this error line:
> 
> ```shell
> s6-overlay-suexec: fatal: can only run as pid 1
> ```
> 
> For the moment, after a quick search, no idea 😞

Maybe you can publish your working tree so we can have a look at the current state

**Comment by Thom-x** [comment]
With something like that it should be working no ? Or is it more an error about s6 itself ?

```
# add bashio (thx https://github.com/hassio-addons/addon-debian-base/blob/main/base/Dockerfile#L47)
ADD https://github.com/hassio-addons/bashio/archive/v0.13.0.tar.gz  /tmp/bashio.tar.gz
RUN apt-get update && apt-get install -y curl jq && mkdir /tmp/bashio \
    && tar zxvf \
        /tmp/bashio.tar.gz \
        --strip 1 -C /tmp/bashio \
    \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio

# add the options.json to environment variable magic
COPY export-env-from-config.sh /export-env-from-config.sh


RUN find /etc/s6-overlay/s6-rc.d/ -name script | xargs sed -i '1 a\source /export-env-from-config.sh'
RUN find /etc/s6-overlay/s6-rc.d/ -name run | xargs sed -i '1 a\source /export-env-from-config.sh'

ENV TZ=UTC

# Add the nice banner

ADD https://raw.githubusercontent.com/hassio-addons/addon-debian-base/v5.1.0/base/rootfs/etc/cont-init.d/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/
RUN mkdir -p /etc/s6-overlay/s6-rc.d/banner && \
    echo "oneshot" > /etc/s6-overlay/s6-rc.d/banner/type && \
    echo "/etc/s6-overlay/s6-rc.d/banner/script" > /etc/s6-overlay/s6-rc.d/banner/up && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/banner && \
    mv /etc/s6-overlay/s6-rc.d/banner/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/script && \
    chmod +x /etc/s6-overlay/s6-rc.d/banner/script && \
    sed -i '1 s/^.*$/#!\/command\/with-contenv bashio/' /etc/s6-overlay/s6-rc.d/banner/script
```

**Comment by Delta1977** [comment]
maybe.
 im, mot the dockerspecialist. but with only with 
`FROM thomx/fr24feed-piaware:1.10.1`
in Max's Dockerfile the error appears.

**Comment by Thom-x** [comment]
So, probably an issue with the new version of s6. 😕

**Comment by Delta1977** [comment]
i found something similar:
https://github.com/zoneminder-containers/zoneminder-base/issues/28

**Comment by Delta1977** [comment]
i testet  "init": false, in config.json and error disapears. so i go on with testing

**Comment by Delta1977** [comment]
yeah that was it.
Dockerfile:
`FROM thomx/fr24feed-piaware:1.10.1

# add bashio (thx https://github.com/hassio-addons/addon-debian-base/blob/main/base/Dockerfile#L47)
ADD https://github.com/hassio-addons/bashio/archive/v0.14.3.tar.gz  /tmp/bashio.tar.gz
RUN apt-get update && apt-get install -y curl jq && mkdir /tmp/bashio \
    && tar zxvf \
        /tmp/bashio.tar.gz \
        --strip 1 -C /tmp/bashio \
    \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio

# add the options.json to environment variable magic
COPY export-env-from-config.sh /export-env-from-config.sh


RUN find /etc/s6-overlay/s6-rc.d/ -name script | xargs sed -i '1 a\source /export-env-from-config.sh'
RUN find /etc/s6-overlay/s6-rc.d/ -name run | xargs sed -i '1 a\source /export-env-from-config.sh'

ENV TZ=UTC

# Add the nice banner

ADD https://raw.githubusercontent.com/hassio-addons/addon-debian-base/v5.1.0/base/rootfs/etc/cont-init.d/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/
RUN mkdir -p /etc/s6-overlay/s6-rc.d/banner && \
    echo "oneshot" > /etc/s6-overlay/s6-rc.d/banner/type && \
    echo "/etc/s6-overlay/s6-rc.d/banner/script" > /etc/s6-overlay/s6-rc.d/banner/up && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/banner && \
    mv /etc/s6-overlay/s6-rc.d/banner/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/script && \
    chmod +x /etc/s6-overlay/s6-rc.d/banner/script && \
    sed -i '1 s/^.*$/#!\/command\/with-contenv bashio/' /etc/s6-overlay/s6-rc.d/banner/script`

and `"init": false` in config.json let start up the addon

**Comment by Delta1977** [comment]
@MaxWinterstein you can find working Config.json and Docker File in my Fork: https://github.com/Delta1977/homeassistant-addons/tree/main/adsb-multi-portal-feeder

**Comment by Delta1977** [comment]
next step could be sort out 
`RUN mkdir -p /etc/s6-overlay/s6-rc.d/banner && \
    echo "oneshot" > /etc/s6-overlay/s6-rc.d/banner/type && \
    echo "/etc/s6-overlay/s6-rc.d/banner/script" > /etc/s6-overlay/s6-rc.d/banner/up && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/banner && \
    mv /etc/s6-overlay/s6-rc.d/banner/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/script && \
    chmod +x /etc/s6-overlay/s6-rc.d/banner/script && \
    sed -i '1 s/^.*$/#!\/command\/with-contenv bashio/' /etc/s6-overlay/s6-rc.d/banner/script`
and add this  direct as files in repo

**Comment by MaxWinterstein** [comment]
note: need to update changelog, readme...

**Comment by MaxWinterstein** [comment]
> next step could be sort out `RUN mkdir -p /etc/s6-overlay/s6-rc.d/banner && \ echo "oneshot" > /etc/s6-overlay/s6-rc.d/banner/type && \ echo "/etc/s6-overlay/s6-rc.d/banner/script" > /etc/s6-overlay/s6-rc.d/banner/up && \ touch /etc/s6-overlay/s6-rc.d/user/contents.d/banner && \ mv /etc/s6-overlay/s6-rc.d/banner/00-banner.sh /etc/s6-overlay/s6-rc.d/banner/script && \ chmod +x /etc/s6-overlay/s6-rc.d/banner/script && \ sed -i '1 s/^.*$/#!\/command\/with-contenv bashio/' /etc/s6-overlay/s6-rc.d/banner/script` and add this direct as files in repo

looks like a good start. flying over the docu it should be possible to have this as a first task, maybe via 
> (legacy) One-shot initialization scripts in /etc/cont-init.d are run sequentially.

Wil have a look some day, time is rare 😞

**Comment by MaxWinterstein** [comment]
Tried a few minutes to get the banner on top, but neither as oneshot nor as (legacy) `cont-init.d`.

It might run first, and just the log is not flushed in the correct sequence, but for the moment i don't really care. In fact, it is better to have it at a lower position so it might be in the truncated log visible at the dashboard.

as adsbexchange is now added, closing this.
