### ISSUE TITLE
GPS Location in Flight Aware.

### ISSUE THREAD

**Issue by benek984** [MaxWinterstein/homeassistant-addons#69]
I have location set in my config:

`
HTML_SITE_LAT: xx.42591
HTML_SITE_LON: x.76998
`
However, in flight-aware status page I can see different gps location and MLAT is disable because of this.
<img width="1528" alt="Maciej_Niedzwiecki_ADS-B_Feeder_Statistics_-_FlightAware_🔊" src="https://user-images.githubusercontent.com/62546477/159296624-c8e8bc48-ba83-4073-9c95-ab7850df3f8b.png">

Any idea what can cause this differences?

**Comment by benek984** [comment]
just to add that I can see MLAT Aircrafts in local status page and adsbexchange

<img width="1747" alt="Home_Assistant" src="https://user-images.githubusercontent.com/62546477/159298020-30b9539c-db8d-43c0-bb5d-0bc46a3ead7c.png">

**Comment by MaxWinterstein** [comment]
Blind guess, but did you provide MLAT Coordinates?

https://github.com/Thom-x/docker-fr24feed-piaware-dump1090#exact-coordinates-for-mlat

**Comment by benek984** [comment]
Hi, yes I did see my .yaml config:

![Notification_Center](https://user-images.githubusercontent.com/62546477/159482012-c31676c7-33c5-46b5-89ac-e96b295c026d.png)

**Comment by MaxWinterstein** [comment]
Another blind guess, did you set your location on the settings page of flightaware?

![image](https://user-images.githubusercontent.com/5927148/160550613-523e00dd-afc6-43a4-b4d9-01bb7b9620f6.png)

**Comment by benek984** [comment]
@MaxWinterstein cant see this in my settings. However since yesterday (after last update of the add-on) all crashed. All services stop and starts in the loop. I had to set: ADSBEXCHANGE_MLAT: 'false' to be able to run the add-on and I set FR24FEED_MLAT: 'no' as in logs shows completely wrong GPS coordinates.

**Comment by MaxWinterstein** [comment]
Well, that should not happen. Will try to reproduce.

**Comment by benek984** [comment]
@MaxWinterstein I found the options to set my coordinates on the flightaware and now MLAT is green but have to keep ADSBEXCHANGE_MLAT: 'false'  as otherwise add on doesn't start. Had to set FR24FEED_MLAT: 'yes' to even see the MLAT aircraft but when looking on the logs my gps coordinates reported to FR24 are offset.

**Comment by MaxWinterstein** [comment]
We might need to tackle down one issue after the other.

Seems like I introduced some typ0 (#75), can you check if your config contains `MLAT_EXACT_LON` **no `G` at the end**?

**Comment by benek984** [comment]
I have both value configured in my config MLAT_EXACT_LON and MLAT_EXACT_LONG . Both contain the same value.

**Comment by benek984** [comment]
> Another blind guess, did you set your location on the settings page of flightaware?
> 
> ![image](https://user-images.githubusercontent.com/5927148/160550613-523e00dd-afc6-43a4-b4d9-01bb7b9620f6.png)

Your suggestion has fixed the issue. 
![Screenshot_29_03_2022__12_50](https://user-images.githubusercontent.com/62546477/160605087-033dcafe-85f9-4358-a385-91e5367e111c.png)

I am happy to close this case and open new one for "Add-on doesnt start when MLAT to adsbexchange is enabled"
