### ISSUE TITLE
CUPS as a add-on

### ISSUE THREAD

**Issue by yousaf465** [MaxWinterstein/homeassistant-addons#74]
Thanks for the excellent add-ons. 
CUPS as an add-on has been requested by many home assistant users. I think @MaxWinterstein can solve this issue.
here is some relevant discussion 
https://github.com/hassio-addons/repository/discussions/248#discussioncomment-2454543
https://github.com/ncarr/addon-repository

**Comment by MaxWinterstein** [comment]
Having some old labelprinter laying around, this is on my wishlist :)

Whats the matter with the one from @ncarr? Does it miss something?

**Comment by yousaf465** [comment]
> Having some old labelprinter laying around, this is on my wishlist :)
> 
> Whats the matter with the one from @ncarr? Does it miss something?

it is not working for me and a few other users. 
Here is a screenshot of it 
![image](https://user-images.githubusercontent.com/83491212/160587194-abc8b1e7-996b-4f98-8e61-7c8ae2d56271.png)

**Comment by MaxWinterstein** [comment]
yeah, seems kinda buggy. Might have a look at this one day, but no promises ✌️

**Comment by MaxWinterstein** [comment]
Did you check https://github.com/hassio-addons/repository/discussions/248#discussioncomment-4326731 - seems like someone fixed the existing one?

**Comment by yousaf465** [comment]
> Did you check [hassio-addons/repository#248 (comment)](https://github.com/hassio-addons/repository/discussions/248#discussioncomment-4326731) - seems like someone fixed the existing one?

I am running HA on RPi4.

**Comment by MaxWinterstein** [comment]
> > Did you check [hassio-addons/repository#248 (comment)](https://github.com/hassio-addons/repository/discussions/248#discussioncomment-4326731) - seems like someone fixed the existing one?
> 
> I am running HA on RPi4.

I see. Tried to install, failed.

**Comment by MaxWinterstein** [comment]
Had a quick play with another repo:

![image](https://user-images.githubusercontent.com/5927148/208203131-88c727b2-914d-4a4d-a3fb-c50782da221d.png)

Works with minimal adjustments, but not sure about the Avahi / Multicast DNS stuff. Need to have a second look later on.

**Comment by yousaf465** [comment]
> Had a quick play with another repo: https://github.com/Luk164/addon-repository
> 
> ![image](https://user-images.githubusercontent.com/5927148/208203131-88c727b2-914d-4a4d-a3fb-c50782da221d.png)
> 
> Works with minimal adjustments, but not sure about the Avahi / Multicast DNS stuff. Need to have a second look later on.

This is on RPi4?

**Comment by MaxWinterstein** [comment]
Yes.

**Comment by yousaf465** [comment]
> Yes.

![image](https://user-images.githubusercontent.com/83491212/208254002-7cb18e1b-2c77-4592-b976-5c2925621150.png)
this one?

**Comment by yousaf465** [comment]
got this ```
Failed to install add-on
The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends cups avahi-daemon libnss-mdns dbus colord printer-driver-all printer-driver-gutenprint openprinting-ppds hpijs-ppds hp-ppd hplip printer-driver-foo2zjs gnupg2 lsb-release && echo "deb http://nginx.org/packages/debian `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list && curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add - && apt-get update && apt-get install nginx nginx-module-njs && apt-get clean -y && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by yousaf465** [comment]
finally worked 
![image](https://user-images.githubusercontent.com/83491212/208254857-07c172dc-0317-49ab-80a2-ecb3a5de5d92.png)
correct repository, and restart fixed it. 
![image](https://user-images.githubusercontent.com/83491212/208254879-a42bb5d9-6fc8-4b57-863d-f1052d93f129.png)

**Comment by MaxWinterstein** [comment]
I just added my running version to this repository. 

Far away from perfect, but should work.

**Comment by yousaf465** [comment]
![image](https://user-images.githubusercontent.com/83491212/209060880-710d09e4-4df5-4ed1-b01d-d4600680a7dc.png)
Atleast Url is working

you need to type "https://192.168.x.x:631" in the address bar to access the page

**Comment by CountParadox** [comment]
x86 here, 
CUPS not accessible by direct IP
![image](https://user-images.githubusercontent.com/6279380/214230774-d69fa340-32d4-424e-8c5c-8ba6899cf4bc.png)

![image](https://user-images.githubusercontent.com/6279380/214230823-3b179406-2465-4fac-a6fa-87ebcaa710ea.png)


![image](https://user-images.githubusercontent.com/6279380/214230857-899acfc1-aafe-4109-8296-845d8568fee1.png)

**Comment by dimmuboy** [comment]
I tried it but unfortunately I'm in the loop of errors :(
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/dbus-setup
cont-init: info: /etc/cont-init.d/dbus-setup exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun avahi (no readiness notification)
services-up: info: copying legacy longrun dbus (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
Found user 'avahi' (UID 104) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.8 exiting.
```

**Comment by MaxWinterstein** [comment]
Will close this as the add-on was added - and improved over the time.
