### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Delta1977** [MaxWinterstein/homeassistant-addons#75]
https://github.com/MaxWinterstein/homeassistant-addons/blob/81acc462840e3d17f143429bbab4973e6372a2d2/adsb-multi-portal-feeder/config.yaml#L87

should be MLAT_EXACT_LON instead MLAT_EXACT_LONG

**Comment by MaxWinterstein** [comment]
oh boy! Thanks, I am so desperate looking at this right now 😮
