### ISSUE TITLE
Add-on doesn't start when MLAT to adsbexchange is enabled

### ISSUE THREAD

**Issue by benek984** [MaxWinterstein/homeassistant-addons#76]
When options 
'
ADSBEXCHANGE_MLAT:
'
 is set to true below error occurs in the logs and add-on keeps stoping and starting in the loop

`
[adsbexchange-conf]31m FATAL: MLAT_EXACT_LAT or MLAT_EXACT_LON or MLAT_ALTITUDE_MSL_METERS or ADSBEXCHANGE_STATION_NAME not set!
`

All mentioned options are set in the config file

**Comment by MaxWinterstein** [comment]
Pls share your config for reproduction. 

Mine, working one:
```yaml
SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: false
SERVICE_ENABLE_FR24FEED: false
SERVICE_ENABLE_HTTP: false
PIAWARE_FEEDER_DASH_ID: 123-123-123-123-123
FR24FEED_FR24KEY: 123
ADSBEXCHANGE_UUID: 123-123-123-123-123
PLANEFINDER_SHARECODE: 123
HTML_SITE_LAT: 50.123
HTML_SITE_LON: 8.123
SERVICE_ENABLE_IMPORT_OVER_NETCAT: true
DUMP1090_REMOTE_HOST: 192.168.1.125
DUMP1090_REMOTE_PORT: 30005
DUMP1090_ADDITIONAL_ARGS: >-
  --net-only --mlat --forward-mlat --net-bi-port 30004,30104 --net-bo-port 30005
  --json-location-accuracy 2 --net-heartbeat 30 --fix --fix
DUMP1090_LOCAL_PORT: 30004
SERVICE_ENABLE_PLANEFINDER: false
MLAT_EXACT_LAT: 50.123
MLAT_EXACT_LONG: 8.123
SERVICE_ENABLE_ADSBEXCHANGE: true
ADSBEXCHANGE_STATION_NAME: 123
MLAT_ALTITUDE_MSL_METERS: 108
MLAT_EXACT_LON: 8.123
```

**Comment by benek984** [comment]
SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: true
SERVICE_ENABLE_FR24FEED: true
SERVICE_ENABLE_HTTP: true
PIAWARE_FEEDER_DASH_ID: 123-123-123-123-123
FR24FEED_FR24KEY: 123-123-123-123-123
ADSBEXCHANGE_UUID: 123-123-123-123-123
PLANEFINDER_SHARECODE: 123-123-123-123-123
HTML_SITE_LAT: 52.123
HTML_SITE_LON: 1.123
SERVICE_ENABLE_ADSBEXCHANGE: true
ADSBEXCHANGE_STATION_NAME: 123-
MLAT_EXACT_LAT: 52.123
MLAT_EXACT_LON: 1.123
MLAT_ALTITUDE_MSL_METERS: 30
HTML_DEFAULT_TRACKER: Flightradar24
HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE: https://uk.flightaware.com/adsb/stats/user/xxxxx
HTML_SITE_NAME: 123-123
HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24: https://www.flightradar24.com/account/feed-stats/?id=xxxx
MLAT_EXACT_LONG: 1.123
ADSBEXCHANGE_MLAT: 'false'
FR24FEED_MLAT: 'yes'
HTML_FR24_FEEDER_STATUS_PAGE: https://www.flightradar24.com/account/feed-stats/?id=xxxxx
SERVICE_ENABLE_PLANEFINDER: true

**Comment by MaxWinterstein** [comment]
Well, still can't really reproduce that. 

One thing worth to note is that your `ADSBEXCHANGE_MLAT: 'false'` contains `false` within quotes, therefore as a string. In the newest release this is now required to be a boolean - so no quotes.

**Comment by benek984** [comment]
Hi, I upgraded to the latest version of the ado-on and now it works.

new version doesn't contain MLAT_EXACT_LONG: 1.123 so I am guessing that was the issue. 
Thank you for your help
