### ISSUE TITLE
How  to check whether adsbexcahnge is working or not?

### ISSUE THREAD

**Issue by yousaf465** [MaxWinterstein/homeassistant-addons#77]
I have enabled all four feeders. I can easily check the feeding status for Fr24, FlightAware and plane finder from their respective sites but how do I check adsbexchange data? 
![image](https://user-images.githubusercontent.com/83491212/160769071-c9c9afa4-a56b-4f18-b2bb-fc985db381d2.png)
![image](https://user-images.githubusercontent.com/83491212/160769229-3a030ab1-fe49-4016-89e9-512534d5b2e2.png)
![image](https://user-images.githubusercontent.com/83491212/160769585-92977953-5b4f-4196-814e-8028b90b8137.png)

**Comment by MaxWinterstein** [comment]
Pls post LOG output and config as yaml (redacted!).

**Comment by yousaf465** [comment]
> Pls post LOG output and config as yaml (redacted!).

`SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: true
SERVICE_ENABLE_FR24FEED: true
SERVICE_ENABLE_HTTP: true
PIAWARE_FEEDER_DASH_ID: 1234abccd
FR24FEED_FR24KEY: 123abcd
ADSBEXCHANGE_UUID: 1234abcd
PLANEFINDER_SHARECODE: 12345abcd
HTML_SITE_LAT: 15.736264 (changed)
HTML_SITE_LON: 52.2312312 (changed)
SERVICE_ENABLE_PLANEFINDER: true
ADSBEXCHANGE_STATION_NAME: ABCD
ADSBEXCHANGE_MLAT: true
MLAT_EXACT_LAT: '52.2312312'
MLAT_EXACT_LON: '52.2312312'
MLAT_ALTITUDE_MSL_METERS: '130'
`
![image](https://user-images.githubusercontent.com/83491212/160777386-7f9314bd-a375-42ea-a751-59cf083fa029.png)

**Comment by MaxWinterstein** [comment]
Isn't there 
```
SERVICE_ENABLE_ADSBEXCHANGE: true
```

missing? 🤔

**Comment by yousaf465** [comment]
> 

I enabled it from UI so I think it was missing there. :P

**Comment by yousaf465** [comment]
![image](https://user-images.githubusercontent.com/83491212/160785075-efa26e0c-083b-4e95-b303-627bf85219ed.png)
@MaxWinterstein I think SERVICE_ENABLE_ADSBEXCHANGE: true is missing in UI so that was the issue. 
Please enable it in UI too. 
You have made our Homeassistant usage a lot easier. keep it up.

**Comment by MaxWinterstein** [comment]
Great! :)

It's visible when enabling this toggle:

![image](https://user-images.githubusercontent.com/5927148/161393788-3cde91ea-7c84-448f-b3f2-73adae3f7379.png)

But, i might overhaul the config part. Its not perfect to me.

Thanks ❤️
