### ISSUE TITLE
Data not being uploaded to Plane finder. 

### ISSUE THREAD

**Issue by yousaf465** [MaxWinterstein/homeassistant-addons#80]
For some strange reason, data is not being uploaded to plane finder.  All other I,e adsb exchange and fr24 are working fine. The only thing that changed is I was running HAOS on an sd card and shifted to a 256Gb SSD and restored backup. If I start using an sd card again it starts working but when I use SSD with the same setup no data is uploaded to the plane finder. 
This bell graph is when I shifted back to the Sd card briefly. 
![image](https://user-images.githubusercontent.com/83491212/165029657-47685e42-75fc-4800-940c-04782b964f0a.png)
on the other hand, Fr24 is working fine 
![image](https://user-images.githubusercontent.com/83491212/165030011-e415e610-3310-4d3b-b76a-1ffb11d7b71b.png)
Adsbexchange 
![image](https://user-images.githubusercontent.com/83491212/165030167-ffc635df-b0df-47f1-bf30-33672d3c617a.png)

My configuration is as follows.
```
SERVICE_ENABLE_DUMP1090: true
SERVICE_ENABLE_PIAWARE: true
SERVICE_ENABLE_FR24FEED: true
SERVICE_ENABLE_HTTP: true
PIAWARE_FEEDER_DASH_ID: xxxxxxxxxxxxxxx
FR24FEED_FR24KEY: xxxxxxxxxxxxxxxxx
ADSBEXCHANGE_UUID: xxxxxxxxxxxxxxxxxxx
PLANEFINDER_SHARECODE: xxxxxxxxxxxxxxxxxxxxxxxx
HTML_SITE_LAT: xx.xxxxxxxxxxxxx
HTML_SITE_LON: xx.xxxxxxxxxxxxxx
SERVICE_ENABLE_ADSBEXCHANGE: true
SERVICE_ENABLE_PLANEFINDER: true
ADSBEXCHANGE_STATION_NAME: xxxx
ADSBEXCHANGE_MLAT: true
MLAT_EXACT_LAT: 'xx.xxxxxxx'
MLAT_EXACT_LON: 'xx.xxxxx'
MLAT_ALTITUDE_MSL_METERS: 'xxx'

```

**Comment by MaxWinterstein** [comment]
Is this still an open thing? 

for the moment I have no clue...

**Comment by yousaf465** [comment]
> Is this still an open thing?
> 
> for the moment I have no clue...

yes, it happens if I use HA from SSD. It resolves I I use an sd card. with same configuration

**Comment by MaxWinterstein** [comment]
Still a thing? If yes - can't really help. Seems not to be really an issue from my side :|

**Comment by yousaf465** [comment]
I think it is fixed on its own. Installed HA again on SSD and it is working so far so good.
