### ISSUE TITLE
Please update your repo

### ISSUE THREAD

**Issue by Delta1977** [MaxWinterstein/homeassistant-addons#82]
Hi, Alex had updated a few adsb tool. Please merge it to your repo

thank you

**Comment by MaxWinterstein** [comment]
Hi @Delta1977, I just pushed some update to `1.15.0` - pls have a test

**Comment by Delta1977** [comment]
Hi @MaxWinterstein , 
thank you. Tit looks good 😄

**Comment by yousaf465** [comment]
> Hi @MaxWinterstein , thank you. Tit looks good 😄

what were the changes?

**Comment by MaxWinterstein** [comment]
Always check https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/releases
