### ISSUE TITLE
octoprint-proxy 

### ISSUE THREAD

**Issue by riclun80** [MaxWinterstein/homeassistant-addons#87]
Hi,
Can get OctoPrint Proxy to work.
After starting the add-on, I get:
"Add-on is not running. Please start it first" or "401: Unauthorized"
when accessing the WEB UI.

The log is saying:
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by Florian14490** [comment]
Same issue here. Everything is up to date.

**Comment by mrwiwi** [comment]
Still here !

**Comment by MaxWinterstein** [comment]
> Still here !

same same :)

It's not forgotten, it's just hard to find time nowadays...

**Comment by tdemelle** [comment]
Just ran across this addon and was hoping it would get octoprint working in my HA install, but ran into this issue.  s6-overlay-suexec: fatal: can only run as pid 1
looks like there's a pull request with a fix, but I don't know enough about how addon containers work to make the fix myself.  If that PR fixes the issue, would be great to get it merged!

**Comment by Florian14490** [comment]
In meantime I use the Mqtt messages from octoprint. Look at the docs octoprint mqtt addon. Works perfect and lots of information

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by MaxWinterstein** [comment]
I just merged the PR by @0nikola1 - should work again.
