### ISSUE TITLE
Adsb-multi-portal-feeder Web UI issue with upgrade to Home Assistant Core 2022.6.4

### ISSUE THREAD

**Issue by chiefcomm** [MaxWinterstein/homeassistant-addons#88]
Since upgrading to Home Assistant Core 2022.6.3 the Web UI is not displaying (all the time), it seems that Dump1090 stops responding randomly.   This is seems to be something introduced with the update to Home Assistant Core 2022.6.2, ADSB feeder all working well prior to 2022.6.3

Configuration:-
Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
ADS-B Multi-Portal Feeder version: 1.15.

**Comment by chiefcomm** [comment]
As FYI I rolled back to earlier version with no luck, I am currently reinstalling and configuring ADS-B Multi-Portal Feeder version: 1.15

**Comment by chiefcomm** [comment]
Resolved by removing ADS-B Multi-Portal Feeder and reconfiguring :-)  Will update on stability in 24hrs, it would be interesting to know if anyone else experience same issue on upgrade to Home Assistant Core 2022.6.x.

**Comment by yousaf465** [comment]
> Resolved by removing and in installing ADS-B Multi-Portal Feeder and reconfiguring :-) Will update on stability in 24hrs, it would be interesting to know if anyone else experience same issue on upgrade to Home Assistant Core 2022.6.x.

working fine here.

**Comment by chiefcomm** [comment]
> > Resolved by removing and in installing ADS-B Multi-Portal Feeder and reconfiguring :-) Will update on stability in 24hrs, it would be interesting to know if anyone else experience same issue on upgrade to Home Assistant Core 2022.6.x.
> 
> working fine here.

Thanks I am switching to a different ADSB dongle as I'm suspecting a hardware issue after finding disturbing entries in the log :-(

**Comment by chiefcomm** [comment]
So disappointingly I have narrowed my issues down to a flakey FlightAware Pro Stick :-(
